- src/session.ts
Hello @xla and @cloudhead!
I created this PR to handle the eventual wallet account change by the user.
Please let me know any edits you need or improvements.
Cheers!
> Handle wallet account change

- src/session.ts
This PR fixes #5.
- It saves the session storage to `LocalStorage`
- Updates the address when it changes
- And removes the session from `LocalStorage` when the user disconnects or Metamask gets closed.
There are some edge cases that Metamask gets locked by the user and does not emit a `accountsChanged` event..
Eventually there will be some kind of lock / unlock event, in the future by Metamask.
The implementation is quite generic and can also work with WalletConnect without great modifications.
> Add session persistence

- tsconfig.json
- types/types.d.ts
This PR closes #9, removing the unnecessary types declaration.
> Remove blockies type

- package-lock.json
- package.json
- src/App.svelte
- src/base/idx/Link.svelte
- src/base/idx/Routes.svelte
- src/config.json
- src/config.ts
- src/session.ts
- src/utils.ts
This PR works on #17 
It implements the [idx protocol by Ceramic](https://developers.idx.xyz/learn/overview/)
To use the functionality in all the different components it adds new properties to and `config` and some `utils` functions that allow read from the idx network.
Since it adds a new protocol and is a bigger feature, I would like to discuss this PR in depth with you @cloudhead to see were you see improvements or need changes.
I'm already working on the usage of these functions in all the components and pages in particular the `getLinkedDid,` and `lookupAddress` but feel it's important to lay down the base first.
To create a did to be used use the idx CLI, we use the 3boxlabs endpoint which can be configured with `idx config:set ceramic-url https://ceramic-clay.3boxlabs.com` …
> Add IDX functionality

- src/Address.svelte
- src/Avatar.svelte
- src/Form.svelte
- src/Header.svelte
- src/base/orgs/Create.svelte
- src/base/orgs/Index.svelte
- src/base/orgs/List.svelte
- src/base/orgs/Org.ts
- src/base/orgs/TransferOwnership.svelte
- src/base/orgs/View.svelte
- src/base/projects/View.svelte
- src/base/registrations/View.svelte
- src/base/resolver/Query.svelte
- src/base/users/View.svelte
- src/base/vesting/Index.svelte
- src/config.json
- src/profile.ts
- src/utils.ts
This PR works on #17 
It brings IDX and ENS identities to all the components where some identity is shown.
For that it implements some new util functions to relieve the components load to create the information to be displayed.
The implementation of the Radicle URN, requires development in collaboration with ceramic-js and the radicle-link team so it will be for another PR.
I welcome feedback since there are some new functions and ways to get profile data into the components.
> User Identity Components

- README.md
The localhost url was outdated showing the port 8080 instead of 3000
> Update README for Vite

- src/Form.svelte
- src/base/registrations/View.svelte
This PR works on #58
It implements a `check` function that validates the entered value by the user with a predefined Regex pattern enum named `validationTypes` created in the `Form` component which can be one of the following types `address`, `url` or `handle`. Which validation should be used is defined in the `fields` array in the `View` component.
The validation happens on the `keyup` DOM Event in the form and defines an `error` value with the corresponding message `Must be a valid ${field.validate}`. This error message supersedes the `description` message under the input field and once corrected reverts to `undefined` so the `description` message can be shown.
It also disables the submit button until the failed validation is corrected by the user.
On mount of the form a copy of the …
> Implement registration form validation

- src/base/registrations/registrar.ts
- src/utils.ts
This PR works on #81 
Reducing the times the resolver contract has to be resolved, and parallelizing some queries.
> Reduce resolver queries and parallelize queries

- src/Avatar.svelte
- src/Header.svelte
- src/base/home/Index.svelte
- src/base/orgs/Index.svelte
- src/base/orgs/List.svelte
- src/base/orgs/Org.ts
- src/config.json
- src/config.ts
- src/utils.ts
> New home page

- .github/workflows/test-e2e.yml
- .gitignore
- cypress.json
- cypress/integration/home.ts
- cypress/integration/org.ts
- cypress/integration/profile.ts
- cypress/integration/project.ts
- cypress/integration/user.ts
- cypress/support/commands.ts
- package-lock.json
- package.json
- src/Form.svelte
- src/base/registrations/registrar.ts
- src/config.json
- src/config.ts
- src/profile.ts
- tsconfig.json
This is a PR working on #12 
Its a first draft, to start talking about which integration tests should be part of a first PR.
Open issues:
Tests to implement:
> Add Cypress for E2E testing

- src/base/projects/Browser.svelte
This PR is a improvement for the issue #32 
It queries all anchors of a project and if the user visits a previous anchored commit it shows how many anchors are in between this commit and the latest, and lets the user navigate to the latest anchor.
_Example of display:_
Works also on responsive
> Improve anchor feature

- public/index.css
- src/base/projects/Browser.svelte
- src/base/projects/Commit/CommitTeaser.svelte
- src/base/projects/Commit/History.svelte
- src/base/projects/Commit/lib.ts
- src/base/projects/Header.svelte
- src/base/projects/View.svelte
- src/project.ts
This PR implements a commit listing, which can be accessed by clicking on the commit count in the project view.
It also:
- Refactors the `Browser` component, extracting the Header in its own component.
- Adds value binding for `commit` and `content` between `View` and lower components `History` and `Header`
- Moves anchor fetching to `Header` component
> Show project commit listing

- src/base/projects/BranchSelector.svelte
- src/base/projects/Header.svelte
This PR provides a better way of toggling project dropdowns, closing any other dropdown that is currently open.
Also should be able to scale to more dropdowns.
Closes #145
> Improve display of project dropdowns

- src/api.ts
- src/base/projects/Browser.svelte
- src/base/projects/ProjectContentRoutes.svelte
- src/base/projects/Routes.svelte
- src/base/projects/View.svelte
- src/base/projects/Widget.svelte
- src/base/registrations/View.svelte
- src/base/registrations/registrar.ts
- src/base/seeds/Seed.ts
- src/base/seeds/View.svelte
- src/config.ts
- src/profile.ts
- src/project.ts
- src/utils.ts
Eg. /seeds/seed.cloudhead.io/projects/:urn
> Support for browsing seed projects

- package-lock.json
- package.json
- src/Markdown.svelte
The markdown shown in the `Markdown` component is defined by the user so we should sanitize it before rendering it with `marked`.
> Sanitize markdown content

- src/Form.svelte
> Improve form validation by showing examples

- src/Form.svelte
- src/base/registrations/View.svelte
> Add link to seed node from registration page

- src/base/projects/Header.svelte
- src/base/projects/Routes.svelte
- src/base/projects/View.svelte
- src/project.ts
> Allow users to pass project names into URL

- src/SeedAddress.spec.ts
- src/SeedAddress.svelte
> By default, use new seed format

- src/base/projects/Project.svelte
- src/base/projects/ProjectRoute.svelte
- src/base/projects/View.svelte
Two minor fixes for the project view reactivity.
- It allows the switching of peers with the selector
- Refetches the remote branches when switching.
> Minor fixes project reactivity

- src/base/seeds/Seed.ts
> Allow URLs to be used for git/api records

- src/Placeholder.svelte
- src/base/projects/Browser.svelte
- src/base/projects/Project.svelte
- src/base/projects/ProjectRoute.svelte
- src/project.ts
Fail gracefully if we can't load a peer.
> Improve project error handling

- cypress/fixtures/groupedCommits.json
- cypress/fixtures/projectCommits.json
- cypress/integration/project.spec.ts
- src/api.ts
- src/base/projects/Commit/CommitTeaser.svelte
- src/base/projects/History.svelte
- src/commit.ts
This PR adds a verified badge to all the commits that have additional peer information, which means that the `http-api` was able to match the commit signature fingerprint to a key available on the seed.
**Things to fix:**
> Verified commits

- src/App.svelte
- src/Diagram.svelte
- src/LinearGradient.svelte
- src/base/orgs/View/Projects.svelte
- src/base/projects/History.svelte
- src/base/projects/Widget.svelte
- src/commit.ts
- src/project.ts
Already working but there are some optimizations left to do.
- General refactoring to make the code simpler.
- Improve the display of the graphs (we have some graphs of peaks where 1 or 2 commits seem the same as 100+ commits in a week)
> Add code activity graph to project widget

- src/base/registrations/New.svelte
- src/base/registrations/registrar.ts
- src/config.json
Since the DAO passed a proposal to remove the registration fee,
we handle that in the UI.
> Remove registration fee

- cypress/integration/project.spec.ts
- src/api.ts
- src/base/projects/History.svelte
- src/base/projects/Widget.svelte
- src/project.ts
> Updates for http-api verified commits change

- cypress/fixtures/projectCommits.json
- cypress/integration/project.spec.ts
Signed-off-by: Sebastian Martinez <sebastinez@me.com>
> Separate project integration tests into smaller cases

- src/base/projects/Commit/CommitAuthorship.svelte
- src/base/projects/Commit/CommitTeaser.svelte
- src/base/projects/History.svelte
> Commit history fixes

- src/App.svelte
- src/SeedAddress.svelte
- src/base/seeds/Routes.svelte
- src/base/seeds/Seed.ts
- src/base/seeds/View.svelte
- src/utils.ts
> Support for `radicle.local` seeds

- cypress/integration/project.spec.ts
Signed-off-by: Sebastian Martinez <sebastinez@me.com>
> Refactor project integration test

- src/base/projects/Issue.svelte
- src/base/projects/Issue/IssueAuthorship.svelte
- src/base/projects/Issue/IssueComment.svelte
- src/base/projects/Issue/IssueTeaser.svelte
- src/issue.ts
This PR improves the `Author` type used in `Issue` and soon in `Patches`, and fixes handling unresolved authors.
> Improve handling unresolved identities

- cypress/e2e/project.spec.ts
- package-lock.json
- package.json
- public/index.css
- src/Popup.svelte
- src/base/projects/Commit/CommitAuthorship.svelte
- src/base/projects/Commit/CommitTeaser.svelte
- src/base/projects/Commit/CommitVerifiedBadge.svelte
- tsconfig.json
> Add verified badge popup

- cypress/e2e/project.spec.ts
- src/base/projects/Header.svelte
- src/base/projects/Project.svelte
> Hide anchored widget behind a feature flag

- src/base/projects/Blob.svelte
This was introduced by a svelte upgrade.
> Fix `<pre>` tag visual bug

- src/base/registrations/Submit.svelte
> fix: redirect to correct page URL after registering a new name and clicking "View"

- src/Diagram.svelte
This PR improves the handling of weekly low commit counts.
**Handling:**
- If the commit count is lower than 5 we set the height to 5.
- Else If the `maxValue` is lower than the `viewBoxHeight`, we show the height corresponding to the commit count without normalization
- Else, once the `viewBoxHeight` gets crossed by the `maxValue` we start to do a linear normalization by max/min values.
**Edge cases:**
- If there was no activity in a year we show a straight line
**Known issues:**
- If there is a big delta between commit counts, the lower data points are disappearing, I did some tests with a linear normalization over logarithmic values, but the issue is that the higher data points level out to be very similar..
_Conclusion_: We should monitor if the graphs now shows better the activity on …
> Improve handling of low commit counts in repo activity

- public/index.css
- src/base/projects/Issue.svelte
- src/base/projects/Patch.svelte
- src/base/projects/Patch/PatchFilter.svelte
- src/base/projects/Patch/PatchTabBar.svelte
- src/base/projects/Patches.svelte
> Styles fixes

- src/base/registrations/Index.svelte
> feat: add name length check at registration

- src/base/projects/Issue/IssueFilter.svelte
- src/base/projects/Issues.svelte
- src/base/projects/Project.svelte
- src/base/projects/ProjectRoute.svelte
- src/base/projects/View.svelte
- src/index.ts
- src/issue.ts
- src/project.ts
- src/utils.ts
> Fix various issue bugs

- package-lock.json
- package.json
- src/Card.svelte
- src/Profile.svelte
- src/base/orgs/Org.ts
- src/base/registrations/registrar.ts
- src/base/resolver/List.svelte
- src/cache.test.ts
- src/cache.ts
- src/profile.ts
- src/utils.ts
This PR adds a wrapper function called `cache` to multiple places where lots of fetching and computing is done, to avoid having lots of Loaders and wait times.
**Pending:**
> Add cache stores and fn

- cypress/e2e/home.spec.ts
- src/base/home/Index.svelte
- src/base/projects/Widget.svelte
- src/config.json
- src/config.ts
- src/project.ts
> Only have projects on home page

- src/Dropdown.svelte
- src/SeedDropdown.svelte
- src/base/projects/BranchSelector.svelte
- src/base/projects/Patch/PatchTabBar.svelte
- src/base/projects/PeerSelector.svelte
This PR closes #254
Adds a way to pass tooltip text to the `Dropdown` component, and more explanations to the Dropdown Trigger button
> Add tooltips for Dropdowns

- src/base/registrations/Index.svelte
> Add small explainer to the name registration form

- src/base/projects/Header.svelte
- src/project.ts
> Improve UX on issue and patches stats in project header

- src/Badge.svelte
- src/base/projects/SourceBrowser/FileDiff.svelte
Cause consistency is 🔑 
(left is proposed)
(left is proposed)
> Style created/deleted badges consistently

- src/base/projects/Header.svelte
> Fix regression in Header component

- public/index.css
- src/Dropdown.svelte
- src/base/orgs/Create.svelte
- src/base/projects/CloneButton.svelte
- src/base/projects/Commit/CommitVerifiedBadge.svelte
We get rid of some of the global styling, because it interacts with styling within components and is hard to reason about. There shouldn't be any visual differences.
> Reduce amount of global styling

- public/index.css
- src/Button.svelte
- src/Connect.svelte
- src/Error.svelte
- src/Form.svelte
- src/Header.svelte
- src/NotFound.svelte
- src/Profile.svelte
- src/RadicleUrn.svelte
- src/Reactions.svelte
- src/SiweConnect.svelte
- src/ToggleButton.svelte
- src/base/faucet/Index.svelte
- src/base/faucet/Withdraw.svelte
- src/base/orgs/Create.svelte
- src/base/orgs/Index.svelte
- src/base/orgs/TransferOwnership.svelte
- src/base/profiles/AnchorActions.svelte
- src/base/projects/Browser.svelte
- src/base/projects/Patch/PatchTabBar.svelte
- src/base/registrations/Index.svelte
- src/base/registrations/New.svelte
- src/base/registrations/Submit.svelte
- src/base/registrations/Update.svelte
- src/base/registrations/View.svelte
- src/base/resolver/List.svelte
- src/base/vesting/Index.svelte
- src/components/Modal/ConnectWallet.svelte
- src/ens/SetName.svelte
We avoid using brittle global styling by extracting buttons into a separate component.
> Extract Button component

- src/base/registrations/New.svelte
- src/components/Modal/ConnectWallet.svelte
> Fix button gap regression

- src/Markdown.svelte
Closes: https://github.com/radicle-dev/radicle-interface/issues/374.
https://user-images.githubusercontent.com/158411/189685484-c8433855-8679-4c6d-9305-9487118b3d2b.mov
> Fix relative markdown links

- src/Header.svelte
Closes: https://github.com/radicle-dev/radicle-interface/issues/368
> Move register button to the right side in the header

- src/Connect.svelte
- src/Search.spec.ts
- src/Search.svelte
- src/base/registrations/Submit.svelte
- src/base/registrations/Update.svelte
- src/base/registrations/View.svelte
- src/base/vesting/Index.svelte
- src/components/TransferOwnership.svelte
- src/ens/SetName.svelte
- src/utils.test.ts
- src/utils.ts
We we're using 50% `...` and 50% `…`.
> Use the ellipsis symbol consistently

- src/base/registrations/View.svelte
Fixes: <img width="391" alt="Screenshot 2022-09-19 at 12 36 14" src="https://user-images.githubusercontent.com/158411/190999723-1492a5c4-dac8-4318-9292-5e49c2dc4b05.png">
> Align Edit button on registration form

- src/base/projects/CloneButton.svelte
Fixes regression introduced in https://github.com/radicle-dev/radicle-interface/commit/d32bad5b62a14413d4a3511b4c1f48d3465b3293.
Before this fix:
After this fix:
> Fix style regression in clone button

- src/config.json
This replaces the one broken project that didn't load and adds 4 more projects.
> Add more pinned projects

- src/TextInput.svelte
> Stop `TextInput` `keydown` event propagation 

- src/base/projects/BranchSelector.svelte
- src/base/projects/CloneButton.svelte
- src/base/projects/Header.svelte
- src/base/projects/PeerSelector.svelte
This PR sets the height of all the project nav buttons to 32px (2rem)
> Fix project nav buttons height

- cypress.config.ts
We have some flaky tests in the test suite. This should take care of it.
E.g.: https://github.com/radicle-dev/radicle-interface/actions/runs/3151541498/attempts/1
> Retry a test twice before giving up

- src/ColorPalette.svelte
> Disable color palette hotkey in production

- src/Comment.svelte
- src/base/projects/Patch/PatchTabBar.svelte
> Fix patch view issues

- .eslintrc.json
- package-lock.json
- package.json
> Upgrade dependencies

- src/Clipboard.svelte
- src/Dropdown.svelte
- src/ErrorModal.svelte
- src/Form.svelte
- src/ReactionSelector.svelte
- src/Reactions.svelte
- src/Search.svelte
- src/TextInput.svelte
- src/base/projects/BranchSelector.svelte
- src/base/projects/Commit/CommitTeaser.svelte
- src/base/projects/Patch/PatchTabBar.svelte
- src/base/projects/PeerSelector.svelte
- src/base/projects/SourceBrowser/FileDiff.svelte
- src/base/projects/Tree.svelte
- src/base/projects/Tree/Folder.svelte
- src/base/registrations/Update.svelte
- src/base/registrations/View.svelte
- src/components/Modal/ConnectWallet.svelte
- src/components/Modal/SearchResults.svelte
- src/ens/SetName.svelte
Adds more compile-time type checks around our usage of Svelte events everywhere in the codebase.
> Make all Svelte events type-safe

- src/Search.svelte
What's on the tin 😎 
Closes #480
> Don't replace history stack when looking up profiles

- src/base/projects/Blob.svelte
- src/base/projects/Commit.svelte
- src/base/projects/Commit/CommitTeaser.svelte
> Add missing twemojis to commit components

- package-lock.json
- package.json
- src/App.svelte
- src/Markdown.svelte
- src/router/index.ts
- src/utils.ts
More optimization, and some refactoring
> Move plausible.js to npm package and improve base handling between hash and history routing

- src/appearance.ts
- src/components/SettingsDropdown.svelte
> Fix minor issues with settings dropdown

- src/Form.svelte
- src/Profile.svelte
- src/base/projects/Readme.svelte
- src/base/seeds/View.svelte
This PR closes issues #508 and #489 
Fix form alignment in `Form` component
Adding rounded bottom radi for the `Readme` component
> Fix design issues

- vite.config.ts
This PR fixes an issue when reloading a page served through `npm run serve` and then trying to reload it.
Since the URL was being passed literally as e.g. `/seeds/clients.radicle.xyz` the server wasn't able to find it.
So the PR checks that the request is not related to a public asset or bundle and if it's a url path it rewrites it to `/index.html`
> Rewrites url for `vite preview` server paths

- package-lock.json
- package.json
> Upgrade transitive dependencies

- public/prettylights.css
- tests/e2e/project.spec.ts
> Fix pretty-lights theme

- .github/workflows/check-build.yml
- .github/workflows/check-e2e.yml
- .github/workflows/check-format.yml
- .github/workflows/check-unit-test.yml
- .github/workflows/check.yml
- package.json
- scripts/check-format
Make sure we're neat and consistent.
> Format yaml files with prettier

- tests/e2e/clipboard.spec.ts
- tests/e2e/hashRouter.spec.ts
- tests/e2e/historyRouter.spec.ts
- tests/e2e/landingPage.spec.ts
- tests/e2e/project.spec.ts
- tests/e2e/project/commit.spec.ts
- tests/e2e/project/commits.spec.ts
- tests/e2e/search.spec.ts
- tests/e2e/seed.spec.ts
- tests/support/fixtures.ts
- tests/support/globalSetup.ts
- tests/visual/project.spec.ts
> Extract fixture specific variables

- src/components/SeedAddress.svelte
- src/lib/api.ts
- src/lib/project.ts
- src/lib/registrar.ts
- src/lib/seed.ts
- src/views/home/Index.svelte
- src/views/profiles/Profile.svelte
- src/views/projects/Header.svelte
- src/views/projects/History.svelte
- src/views/projects/View.svelte
- src/views/projects/Widget.svelte
- src/views/registrations/View.svelte
- src/views/seeds/View.svelte
- src/views/seeds/View/Projects.svelte
```
seed.api -> seed.addr
seed.link -> seed.node
```
> Rename Seed class attributes

- src/lib/router.ts
- src/views/projects/Header.svelte
- src/views/projects/Issues.svelte
- src/views/projects/Patches.svelte
There were some issues in how we handled the state param in the url querystring in the issue and patch listings.
This commit should improve this, and allow for better usage of querystring params in the future.
Closes #531
> Fix querystring handling for issues and patches

- scripts/run-http-api-with-fixtures
- src/lib/commit.ts
- src/lib/diff.ts
- src/lib/patch.ts
- src/lib/project.ts
- src/views/projects/SourceBrowser/Changeset.svelte
- src/views/projects/SourceBrowser/FileDiff.svelte
- tests/e2e/project/commit.spec.ts
> Add Heartwood translation layer for file diffs

- src/App/Header/Search.svelte
Whats written on the tin
Closes #569
> Reset search input on user navigation

- src/views/profiles/Profile.svelte
Formats ETH addresses always in Profile page title
See for reference #555
> Always format ETH address in Profile component

- src/App/Header.svelte
Fixes https://github.com/radicle-dev/radicle-interface/issues/598.
> Use cursor pointer for settings button

- public/colors.css
- src/App/Header/SettingsDropdown.svelte
- src/components/Dropdown.svelte
- src/components/TextInput.svelte
- src/components/ToggleSwitch.svelte
- src/views/projects/Blob.svelte
- src/views/projects/CloneButton.svelte
- src/views/projects/Commit.svelte
- src/views/projects/Commit/CommitTeaser.svelte
- src/views/projects/History.svelte
- src/views/projects/Readme.svelte
- src/views/projects/SourceBrowser/FileDiff.svelte
- src/views/projects/Widget.svelte
Adds new elevation variable which adds better contrast in light mode closes #507 
Signed-off-by: Brandon Oxendine <brandon.oxendine@gmail.com>
> New elevation variable

- src/App/Header/Connect.svelte
- src/lib/session.ts
- fixes copy button alignment
vs
- fixes mixed content error
> Improve session feature

- src/lib/session.ts
- src/lib/utils.ts
This disconnects the frontend in case the backend is not online anymore or if the session has expired.
> Poll session every minute to make sure we are still connected

- .github/workflows/check-visual.yml
Fix visual diffs. Now for real.
https://github.com/radicle-dev/radicle-interface/actions/runs/4416666423/jobs/7741273348
> Don't try to find comment on master for visual diffs

- src/config.json
> Pin radicle-team repo

- src/components/Authorship.svelte
- src/components/Chip.svelte
- src/components/Comment.svelte
- src/components/Dropdown.svelte
- src/components/DropdownButton.svelte
- src/components/Markdown.svelte
- src/components/TextInput.svelte
- src/components/Textarea.svelte
- src/components/Thread.svelte
- src/lib/api.ts
- src/lib/cobs.ts
- src/lib/issue.ts
- src/lib/utils.ts
- src/views/projects/BranchSelector.svelte
- src/views/projects/Issue.svelte
- src/views/projects/Issue/IssueHeader.svelte
- src/views/projects/Issue/IssueSidebar.svelte
- src/views/projects/Issue/IssueStateButton.svelte
- src/views/projects/Issue/IssueTeaser.svelte
- src/views/projects/Issue/New.svelte
- src/views/projects/PeerSelector.svelte
- src/views/projects/View.svelte
- tests/unit/cobs.test.ts
This PR will add to issues:
- Add threads
- Add replies
- Edit assignees & tags
- Manage lifecycle
> Issue editing

- src/components/TabBar.svelte
- src/lib/utils.ts
- src/views/projects/Issues.svelte
- src/views/projects/Patch.svelte
- src/views/projects/Patches.svelte
> Use capitalize from lodash

- src/lib/utils.ts
- src/views/projects/CloneButton.svelte
- src/views/projects/Header.svelte
- tests/e2e/clipboard.spec.ts
- tests/e2e/hashRouter.spec.ts
- tests/e2e/historyRouter.spec.ts
- tests/e2e/project.spec.ts
- tests/support/fixtures.ts
This should work when the app is deployed somewhere other than localhost.
> Fix mixed content warning when connecting to local node

- scripts/run-httpd-with-fixtures
Depends on https://github.com/radicle-dev/heartwood/pull/514 being merged first
> Migrate off of Google Cloud Storage

- src/components/Badge.svelte
- src/components/DiffStatBadge.svelte
- src/views/projects/Patch.svelte
- src/views/projects/Patch/PatchTeaser.svelte
See PR title
Closes #662, #667
> Update patch state colors and DiffStatBadge contrast

- src/components/Comment.svelte
> Remove `word-break: break-all` from `Comment` component

- src/App/Header/Search.svelte
- src/App/Hotkeys.svelte
- src/lib/shared.ts
- tests/e2e/hotkeys.spec.ts
- tests/e2e/search.spec.ts
> Rename the search bar placeholder

- httpd-client/lib/project/patch.ts
- src/views/projects/Issues.svelte
- src/views/projects/Patch.svelte
- src/views/projects/Patches.svelte
We now also show an error message to the user instead of silently failing if there's an error fetching or a schema mismatch.
<details>
<summary>When copied to clipboard we see the full stack trace and data:</summary>
```json
{
"errorMessage": "Could not load patches",
"stackTrace": {
"method": "GET",
"path": "projects/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/patches",
"body": [
{
"id": "9966151abfd6f085dbe8501c6eb149c8a3f48d81",
"author": {
"id": "did:key:z6MkgFq6z5fkF2hioLLSNu1zP2qEL1aHXHZzGH1FLFGAnBGz"
},
"title": "tui: Update navigation design",
"description": "",
"state": {
"status": "open"
},
"target": "delegates",
"tags": [],
"revisions": [
{
"id": "9966151abfd6f085dbe8501c6eb149c8a3f48d81",
"description": "",
"base": "bd0482622393556cdcdc32cfab7fdea4fbf64ab5",
"oid": …
```
> Fix httpd-client patch review verdict schema

- index.html
We weren't preloading all the fonts that we are using which caused them to swap after the render.
> Fix font preloading

- src/components/InlineMarkdown.svelte
- src/components/Markdown.svelte
- src/views/projects/Cob/CobHeader.svelte
- src/views/projects/Commit.svelte
- src/views/projects/Commit/CommitTeaser.svelte
- src/views/projects/Issue/IssueTeaser.svelte
- src/views/projects/Patch/PatchTeaser.svelte
Closes https://github.com/radicle-dev/radicle-interface/issues/699.
> Allow markdown in issue/patch titles

- httpd-client/lib/project/patch.ts
- src/components/Authorship.svelte
- src/views/projects/Patch/PatchTeaser.svelte
> Add `alias` to PatchTeaser

- httpd-client/lib/project/issue.ts
- src/views/projects/Issue.svelte
- src/views/projects/Issue/IssueTeaser.svelte
> Add `alias` to `Issue`/`IssueTeaser`

- httpd-client/lib/project/comment.ts
- src/components/Comment.svelte
- src/components/Thread.svelte
> Add `alias` to `Comment`

- httpd-client/lib/project.ts
- src/components/Dropdown.svelte
- src/views/projects/PeerSelector.svelte
**selector:**
**delegate with alias:**
**selected remote with alias:**
> Add `alias` to `PeerSelector`

- src/App/ColorPaletteModal.svelte
- src/components/Badge.svelte
- src/components/DiffStatBadge.svelte
- src/views/projects/CloneButton.svelte
- src/views/projects/Cob/Revision.svelte
- src/views/projects/Issue.svelte
- src/views/projects/Issue/IssueTeaser.svelte
- src/views/projects/Patch.svelte
- src/views/projects/Patch/PatchTeaser.svelte
- src/views/projects/SourceBrowser/Changeset.svelte
Uses the same colors for issue/patch icons and diff stat badges everywhere consistently.
> Use colors in badges and icons consistently

- src/components/Comment.svelte
- src/components/Thread.svelte
- src/views/projects/Cob/Revision.svelte
Show either an `Authorship` component if no review comment is available or a `CommentComponent` if there is a comment.
Also add a positive or negative background to `CommentComponent` depending on verdict
> Fix showing Authorship and CommentComponent for review twice

- src/views/projects/Patch/PatchTeaser.svelte
Closes https://github.com/radicle-dev/radicle-interface/issues/799.
> Move comment counter before the diff stat badge

- src/views/projects/Commit.svelte
> Add font-family monospace to commit description

- src/components/Comment.svelte
- src/views/projects/Cob/Revision.svelte
> Move commits inside the `action` div

- src/components/Icon.svelte
- src/components/SquareButton.svelte
- src/views/projects/Header.svelte
- src/views/projects/PeerSelector.svelte
Closes: https://github.com/radicle-dev/radicle-interface/issues/810.
> Add 16x16 icons to project header

- .eslintrc.json
- package-lock.json
- package.json
Just for my and @rudolfs sanity hehe
> Add no-only-test linter rule

- src/views/projects/Blob.svelte
- src/views/projects/router.ts
See individual commits for details
> Project routing: fix markdown mode and initial loading

- src/views/projects/View.svelte
- src/views/projects/router.ts
Follow up on https://github.com/radicle-dev/radicle-interface/pull/767.
> Move issue loading into the router

- src/views/projects/View.svelte
- src/views/projects/router.ts
Follow up on https://github.com/radicle-dev/radicle-interface/pull/767.
> Move patch loading to router

- src/views/projects/Patch.svelte
This is a regression we introduced in https://github.com/radicle-dev/radicle-interface/pull/767.
> Fix patch revision selector

- src/config.json
We should have at least one repo with a `awesome` prefix under the pinned repos 😎
> Add awesome-radicle to pinned repos

- src/views/projects/Issue.svelte
- tests/support/fixtures.ts
Adds also a root level comment to the cobFixture to avoid margin regressions between root level comments
Closes #832
> Add margin between comment threads in issue view

- src/views/projects/Issue/New.svelte
- src/views/projects/Issues.svelte
- src/views/projects/Patch.svelte
- src/views/projects/Patches.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
Move everything that is sub-view related into the respective views.
> Simplify project view

- httpd-client/lib/project/comment.ts
This fixes the broken issue list on heartwood: https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/issues?state=closed.
> Fix comment schema

- httpd-client/index.ts
- src/App/Header/Connect.svelte
- src/App/Header/Search.svelte
- src/App/Header/SearchResultsModal.svelte
- src/lib/router.ts
- src/lib/utils.ts
- src/views/home/Index.svelte
- src/views/projects/Header.svelte
- src/views/projects/Issue.svelte
- src/views/projects/Issue/New.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
- src/views/seeds/View.svelte
- src/views/seeds/router.ts
- src/views/session/Index.svelte
- tests/e2e/hashRouter.spec.ts
- tests/e2e/historyRouter.spec.ts
- tests/unit/router.test.ts
To make the code easier to reason about we handle all app URL encoding and decoding and the related seed BaseUrl extraction in a single place.
> Handle app URL translation into seed BaseUrl one place

- src/components/Markdown.svelte
- src/views/projects/Blob.svelte
- src/views/projects/Browser.svelte
- src/views/projects/Tree.svelte
- src/views/projects/Tree/Folder.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
- tests/e2e/project.spec.ts
We move Blob loading into the router.
> Extract project blob loading into the router

- src/lib/syntax.ts
- src/views/projects/Blob.svelte
- src/views/projects/Browser.svelte
- src/views/projects/router.ts
> Run source highlighting in router to prevent showing intermediate state

- src/views/projects/Cob/Revision.svelte
- src/views/projects/Patch.svelte
> Replace patch author with revision author in Revision component

- src/views/projects/BranchSelector.svelte
- src/views/projects/Browser.svelte
- src/views/projects/Commit.svelte
- src/views/projects/Header.svelte
- src/views/projects/History.svelte
- src/views/projects/SourceBrowsingHeader.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
This simplifies the Project top level view.
> Clean up Project Header and SourceBrowsing header props

- src/components/Comment.svelte
- src/components/InlineMarkdown.svelte
- src/components/Markdown.svelte
- src/components/Thread.svelte
- src/lib/markdown.ts
- src/lib/router.ts
- src/views/projects/Blob.svelte
- src/views/projects/Browser.svelte
- src/views/projects/Cob/Revision.svelte
- src/views/projects/Issue.svelte
- src/views/projects/Issue/New.svelte
- src/views/projects/Patch.svelte
- src/views/projects/Readme.svelte
We completely rewrite markdown link handling to address [this comment](https://github.com/radicle-dev/radicle-interface/pull/900#pullrequestreview-1516015310) in #900 and also tackle part of #902.
> Rewrite markdown link navigation

- src/components/SquareButton.svelte
- src/views/projects/Blob.svelte
- tests/e2e/project.spec.ts
> Don’t leave line selected when switching blobs

- src/views/projects/router.ts
*Based on #921 so only the last commit is relevant*
We refactor the code that builds a URL from a project route so that it is clearer that only the `tree` and `history` resource have some complicated logic. We also eliminate the use of the shared `suffix` variable. We now build the URL left-to-right.
> Improve resource separation in route URL building

- src/views/projects/Patch.svelte
Fixes the second post of https://github.com/radicle-dev/radicle-interface/issues/925
> Use correct tree hash for file path on diff page

- src/views/projects/router.ts
The `loadProjectRoute` function has become too big too understand. To address this, we extract and separate the loading for the `tree` and `history` views. This also gives us the opportunity to simplify some of the code and parallelize more HTTP requests.
> Extract tree and history route loading

- src/views/projects/Patches.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
We move the project list loading to the router.
> Load patch list in project router

- src/views/projects/Issues.svelte
- src/views/projects/Patches.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
Based on https://github.com/radicle-dev/radicle-interface/pull/968.
> Load issue list in project router

- src/views/projects/Issues.svelte
- src/views/projects/Patches.svelte
Together with the project refactoring, this fixes https://github.com/radicle-dev/radicle-interface/issues/691.
> Make issues/patches tab counters reactive

- src/views/seeds/View.svelte
> fix: Make seed hostname reactive in seed project listing

- src/views/projects/Issue.svelte
- src/views/projects/Issue/New.svelte
- src/views/projects/Issues.svelte
- src/views/projects/Patch.svelte
- src/views/projects/View.svelte
We simplify the properties of the project views `Issue`, `Issues`, `NewIssue`, and `Patch`. This aligns them with other project views and makes the view selection consistent.
> Simplify and align project view props

- src/config.json
> Pin radicle-homepage and radicle-tui to the landing page

- tests/e2e/project/issues.spec.ts
Adds a small test to complete #897
> Add test to check that issue counter updates when closing issue

- src/components/Comment.svelte
- src/components/Icon.svelte
- src/components/ReactionSelector.svelte
- src/components/Reactions.svelte
- src/views/projects/Issue.svelte
- tests/e2e/project/issues.spec.ts
- tests/e2e/project/patches.spec.ts
To adapt to different form factors, this PR refactors some of the reactions elements.
Some images:
> Refactor some of the reaction components
