- src/base/orgs/Org.ts
- src/base/registrations/registrar.ts
- src/base/registrations/resolver.ts
- src/base/vesting/vesting.ts
- src/config.json
- src/config.ts
- src/session.ts
Hello @cloudhead,
I was looking into the registration workflow and thought it would be a good idea to check the users RAD balance to be higher than the`registrar.registrationFeeRad` before sending the tx, looking into this I started to extract all the contract ABIs into the `config.json` file.
IMHO the code gets cleaner and it reduces code duplication.
Please let me know what you think.
Cheers
> Extract contract abis to config.json

- src/config.ts
- src/session.ts
This PR closes #10 
It uses the `window.ethereum.on('chainChanged')` event from Metamask, and in the `config.ts` constructor checks if the network is supported.
Eventually we could disable the connect button if the network is not supported instead of the fullscreen error, or change the current fullscreen `<Modal>` error with the `<Error>` component used by failed transactions.
Please let me know what you think @cloudhead
> Validate network and reloads on change

- src/base/registrations/registrar.ts
- src/error.ts
Hi @cloudhead,
Sorry for the consecutive PRs but I wanted to build upon the ABIs refactoring with this PR, and I don't like to propose changes of different kind in the same PR.
Trying to register my name yesterday I spend fee for a tx without having enough RAD tokens, so the idea is to stop the user that he has not enough RAD to register a name before he spends ETH in the tx.
I'm also thinking about writing some kind of util function for the construction of the `ethers.Contract` instance
Cheers
> Validate RAD balance before commit tx

- src/ens/SetName.svelte
Hi @cloudhead 
Found this little bug that prevented one to set a name to a orgs, we were comparing checksummed address against lowercase addresses.
I used the `isAdressEqual` util function to fix it.
> Fix address comparison in ens/SetName

- .eslintignore
- .eslintrc.js
- .github/workflows/check-format.yml
- scripts/check-format
This PR closes #6 
I used `prettier` and `prettier-plugin-svelte` to implement a code formatter.
The configuration is pretty simple and originally from `radicle-upstream` with some minor changes for this repo.
To be able to use GitHub CI I created a very bare GitHub Action, and the core is in the shell script `scripts/format`
Let us discuss here which format options are the correct ones for this repo
https://prettier.io/docs/en/options.html
> Implement code formatter

- src/session.ts
This PR resolves the issue with the balance that does not update itself when a network change happens.
Eventually there is a cleaner way to obtain the `config` needed by `state.refreshBalance`
> Refresh balance after a network change

- src/Address.svelte
- src/App.svelte
- src/Avatar.svelte
- src/base/users/Routes.svelte
- src/base/users/View.svelte
This PR works on #17
- It implements a new User route `/users/:address` which shows a user profile, with avatar or blockies as a fallback and the profile links.
- Adds a loading flag to show only the final state of the profile
- If one access the route with a contract address it also shows the stored information on ENS.
- Removes the Blockies from the Address component, so it can be decided by each page if it wants to show.
To test the implementation you could use the address `0xef1B2D659F4662f6a1e4a1B4791A1B4cEFF8FbA1` for sebastinez.rad.eth
> Add User View Route

- vite.config.ts
This PR fixes the issue with gnosis safe trying to read `process.env` in the browser and forces it to use our stream polyfill.
> Add READABLE_STREAM process env

- src/ens/SetName.svelte
Trying to set a name for a newly created single owner org I found that checking if the org address was a safe it failed.
After a little debugging session, I found the `isSafe` function that returns a promise was not being awaited in the `SetName` component.
Let me know if you want me to squash this commit somewhere, or if you want to commit it with other changes.
I created the PR to implement this fix asap
> Add await to isSafe check

- src/BlockTimer.svelte
- src/base/registrations/Submit.svelte
- src/base/registrations/registrar.ts
This PR solves #33
It implements a new component called `BlockTimer` that could eventually be used in other use cases where one has to wait for a specific quantity of blocks to be mined.
It takes a starting block number and the number of blocks it needs to fill up to 100%.
To implement it in the registration process I did some changes to the `Connection` type to implement the `commitmentBlock` and `minAge`, and avoid refetching it later.
P.S. For some reason the `tx` object in the `commit` fn in `registrar.ts` did not include blockNumber or hash, thats why I'm feching the tx receipt to obtain the `commitmentBlock`
> Add commitment progress bar

- src/config.json
This PR fixes #47 with adding the mainnet gnosis safe to the `config.json` file.
> Add Gnosis Safe Mainnet to config

- src/Address.svelte
- src/Header.svelte
- src/base/orgs/Org.ts
- src/base/orgs/View.svelte
- src/base/projects/Browser.svelte
- src/base/projects/View.svelte
- src/base/registrations/View.svelte
- src/base/registrations/registrar.ts
- src/base/users/View.svelte
- src/profile.ts
- src/utils.ts
Introduce two types of profile: a 'full' and a 'minimal'.
The minimal is used when only the avatar is required, which
is in most places. Requests for an org view is reduced by 3x.
Closes #72
> Reduce number of requests for profiles

- src/profile.ts
I think we can safely reduce the calls to the IDX, if we only call it after checking that the ENS profile came back `null`
Since every call to IDX took about 400ms+ it makes some pages more responsive.
> Reduce calls to IDX profile streams

- src/base/users/View.svelte
This PR works on issue #70 
It adds two fields to the user page.
- First the address of the user, for quick reference
- And more importantly for UX the profile of the user with a link that leads to the registration form (equal to the orgs profiles)
> Add fields to user profile

- src/config.ts
This PR works on #71
It implements a function called `checkMetaMask` that awaits the `metamask.ready` promise and if after 4 seconds Metamask didn't return the network it returns null.
We check the return value and `if == null` we throw a new Error and avoid the infinite spinning.
> Fix multiple wallets

- src/base/orgs/View.svelte
- src/base/users/View.svelte
- src/config.json
- src/config.ts
- src/profile.ts
This PR is the continuation of #80 
It adds a `registry(config: Config)` to the `Profile` class, which returns either a link to the client registration form or in case of IDX to the https://self.id webapp.
> Add registry method to Profile

- src/base/registrations/Submit.svelte
- src/base/registrations/View.svelte
- src/base/registrations/registrar.ts
This PR works on #65 
It checks if the `status` of the view is `NotFound` and in which case it starts recursively to retry fetching the information, until reaching 3 retries.
To avoid refetching the resolver contract it caches it with the first try.
> Refresh registration form

- src/Address.svelte
- src/Avatar.svelte
- src/Header.svelte
- src/base/orgs/List.svelte
- src/base/orgs/View.svelte
- src/base/projects/View.svelte
- src/base/users/View.svelte
This PR works on #91 
It allows images that return `404` or somehow are not able to be loaded into an `img` tag to be replaced by a blockies image.
To simplify the component I reduce it to a simple `img` tag that shows the avatar url or the blockies dataUrl depending on the initial props or the error handling function.
I defined `address` as a required prop, since we never show a avatar without providing an address.
There is still improvements possible.
Feel free to provide feedback
> Show blockies when avatar image is missing

- src/base/orgs/View.svelte
- src/utils.ts
This PR implements #99 
It completes the function `utils.getTokens` providing a way to obtain with the Alchemy Token API the top 100 tokens by 24 hour volume.
When an Multi-Sig Org profile is opened and the Org has ETH or some ERC20 top 100 token an additional field called `Treasury` is being shown and a horizontal list of the ETH and other treasured ERC20 tokens is being shown.
In case of a EOA or other address type nothing is shown.
In case that Metamask is being used nothing is shown since the Alchemy API is not being supported.
> Add Org treasury to org profile

- src/base/orgs/Org.ts
- src/profile.ts
- src/utils.ts
This PR allows us to reduce the amount of API calls we do to the Gnosis Safe API and use the new introduced Subgraph Schema were we index the safes of a org.
There is a small caveat that we need to query for org owners and org members separately in the `getOrgsByMember` function since we can't do a OR query for one or the other, left a `TODO` there if this gets implemented in the future.
It also moves the console errors filling IDX errors to a much less invasive `console.debug`
This PR depends on the PR on the `radicle-subgraph` repo so we should wait with merging until the subgraph got updated.
https://github.com/radicle-dev/radicle-subgraph/pull/4
> Change Gnosis Safe calls to Subgraph

- src/components/Modal/ConnectWallet.svelte
- src/config.json
- src/config.ts
- src/session.ts
- src/utils.ts
This PR fixes #66 
- Starts using Alchemy as Rinkeby provider, leaves Metamask as signer and for dev environment.
- Allows changing accounts and network through WalletConnect on the go, no need to manually refresh the page
- In case of using Metamask, the UI requests Metamask for a network change, which the user has to confirm (**Does not work with Brave Wallets, only with Metamask**)
- In case of a network mismatch, forces the UI to change to the network of the linked WalletConnect app
- Updates the available wallets link
As always feel free to drop your thoughts :smile:
> Handle WalletConnect network change

- src/base/orgs/Org.ts
- src/base/users/View.svelte
This PR closes #98 
It adds a listing equal to the org member listing, to show which orgs a user is member of, and allows
It uses multiple static functions of the Org class to get the information and lets the visitor jump directly to a specific org.
> Show orgs in user profile

- src/Card.svelte
- src/Cards.svelte
- src/WalletConnectSigner.ts
- src/base/home/Index.svelte
- src/base/registrations/registrar.ts
- src/profile.ts
- src/utils.ts
This PR closes #113 
It does so by showing a simplified `Card` while loading the `Profile` details like avatar, name, etc.
```svelte
{#await Profile.get(org.name ?? org.address, ProfileType.Minimal, config)}
<Card profile={{ address: org.address }} {config} path={`/orgs/${org.address}`} />
{:then profile}
{#if orgMembers[profile.address]?.length}
<Card {profile} {config} path={`/orgs/${profile.nameOrAddress}`} members={orgMembers[profile.address]} />
{:else}
<Card {profile} {config} path={`/orgs/${profile.address}`} />
{/if}
{/await}
```
It also implements some fixes to `null | undefined` as arguments and return values.
We should eventually conform in the entire codebase to one of the two null types and try to cast them to the corresponding one where needed from third party libraries …
> Improve loading of Cards component

- src/Form.svelte
- src/api.ts
- src/base/projects/Browser.svelte
- src/base/projects/View.svelte
- src/base/registrations/View.svelte
- src/base/registrations/registrar.ts
- src/base/registrations/resolver.ts
- src/config.json
- src/config.ts
- src/profile.ts
- src/utils.ts
Adds two new records:
* eth.radicle.seed.api
* eth.radicle.seed.git
When specified, these override `eth.radicle.seed.host` for Git
and the HTTP API, respectively.
> Allow overriding eth.radicle.seed.host record

- src/base/orgs/Org.ts
- src/base/orgs/View.svelte
- src/base/projects/View.svelte
- src/base/users/View.svelte
Removes also some `getProfile` functions that were only used once or twice.
> Remove org owner fallback in getProfile

- src/base/users/Routes.svelte
- src/base/users/User.ts
- src/base/users/View.svelte
- src/ens/SetName.svelte
This PR closes #42 
It uses the already working `SetName` component for orgs and implements it for users, to allow a fast reverse record setting after registering their subdomain
> Allow users set reverse records

- src/Avatar.svelte
- src/base/orgs/Org.ts
- src/base/orgs/View.svelte
- src/base/orgs/View/Anchor.svelte
- src/base/orgs/View/Projects.svelte
- src/base/projects/Widget.svelte
- src/config.json
- src/project.ts
- src/utils.ts
This PR closes #39 
It allows the signing and execution of anchor proposals for gnosis safe orgs.
**Some interesting points:**
- At the moment a pending project requires at least the required confirmations, once received the threshold, we don't accept more confirmations, but allow to execute the safe transaction.
- The owners that signed the proposal, show up as blockies, we could eventually show the profile avatar or show something entirely different, IMO the blockies maintain the design of the rest of the page.
> Manage anchor proposals

- vite.config.ts
This PR adds the `base` property to the `vite.config.ts` this allows the assets to be defined from a relative path in `index.html`.
https://github.com/vitejs/vite/issues/762#issuecomment-711167905
This is necessary for a proper implementation of issue #40 which has issues with absolute paths when serving the UI from a IPFS gateway.
I did also run the E2E Cypress test suite after this change to verify that we won't have issues by running it outside of IPFS.
> Change asset paths to be relative

- src/App.svelte
- src/api.ts
- src/base/orgs/View.svelte
- src/base/orgs/View/Projects.svelte
- src/base/projects/Widget.svelte
- src/base/registrations/registrar.ts
- src/base/seeds/Routes.svelte
- src/base/seeds/Seed.ts
- src/base/seeds/View.svelte
- src/config.ts
- src/profile.ts
- src/project.ts
- src/utils.ts
This PR adds a page to explore the projects of a particular seed/org node.
If the seed is on v0.2.0 or above it shows the peer id and the projects that the seed node follows.
If not it shows a text, that some funcionality is limited, and one should upgrade to v0.2.0
It also does the following;
- moves the Seed class to the seed folder
- Adds some null types, to allow passing null as argument eg. into the Seed class 
- Changes to the Widget component, to allow projects that don't have a anchor hash.
- Link from the org page to the new seed page
> Add seed page

- src/base/projects/BranchSelector.svelte
- src/base/projects/Browser.svelte
- src/base/projects/Commit/History.svelte
- src/base/projects/Header.svelte
- src/base/projects/ProjectContentRoutes.svelte
- src/base/projects/Routes.svelte
- src/base/projects/View.svelte
- src/base/projects/Widget.svelte
- src/project.ts
- src/utils.ts
This PR provides:
- Adds URL support for project routes:
- For commit listing under `/users/:user/projects/:urn/history/:commit`
- The tree view you'll find under `/users/:user/projects/:urn/tree/:commit`
- and as fallback we show the tree view
- Adds branches selector to the `Header` that allows selecting the different head commits wrt to the selected branch
> Project url support and branch browsing

- src/base/projects/Browser.svelte
- src/base/projects/Commit/History.svelte
- src/base/projects/Header.svelte
- src/base/projects/ProjectContentRoutes.svelte
- src/base/projects/View.svelte
Fixes lack of reactivity when you:
1. open file browser, choose a file, then press back
2. open history browser, switch between branches, then press back
Also simplifies things by using two-way bindings instead of events.
> Reactivity fixes

- src/Icon.svelte
- src/base/projects/BranchSelector.svelte
- src/base/projects/Browser.svelte
- src/base/projects/Header.svelte
- src/base/projects/PeerSelector.svelte
- src/base/projects/ProjectContentRoutes.svelte
- src/base/projects/Routes.svelte
- src/base/projects/View.svelte
- src/base/seeds/View.svelte
- src/project.ts
This PR adds the ability to select available peers to a project limited to the seed page
- Peer selection through the peer selector in the project header.
- If no peer listing is available the peer selector won't show.
Closes #134
> Add peer selector

- src/Avatar.svelte
This PR uses the `object-fit` attribute to the Avatar component, so that the avatars fill their container, if they are not perfectly square. Which in most cases should keep it the same but in some cases maintains the form factor of the Avatars
Closes #155
> Fix avatar aspect ratio

- src/base/orgs/View.svelte
- src/utils.ts
Passes the `decimals` property from Alchemy to `ethers.utils.formatUnits`, if `formatBalance` is used without decimals it defaults to convert wei to ether
`ethers.utils.formatUnits( value [ , unit = "ether" ] ) ⇒ string`
> Fix Org Treasury token balances

- src/anchors.ts
- src/base/projects/Header.svelte
- src/base/projects/ProjectContentRoutes.svelte
- src/base/projects/View.svelte
This PR closes #132 
- Moves anchor retrieval back into the `View` component.
- Passes resolved anchors into `Header` component, if no anchors available, returns an empty array which is falsy and `Header` won't show any anchor
- If no commit is passed to `View` component, checks first for latest anchor, and else uses head commit.
> Show project with anchor when no commit hash passed

- src/base/projects/Browser.svelte
- src/base/projects/Commit/History.svelte
- src/base/projects/Header.svelte
- src/base/projects/PeerSelector.svelte
- src/base/projects/ProjectContentRoutes.svelte
- src/base/projects/View.svelte
- src/project.ts
We had a lot variables that we had to pass down from the project view,
and only very few where important to the reactivity of the components.
By using the resolved Promise from `getProject` as transport we can use
now the `source` variable and get the required params by destructuring
it.
In short we can pack now the following params:
```
urn, org, user, seed, peer, project, branches, peers, config, anchors
```
> Refactor source params into separate object

- src/base/orgs/Org.ts
- src/base/orgs/View.svelte
- src/base/orgs/View/Anchor.svelte
- src/base/orgs/View/Projects.svelte
This PR fixes the workings of `Org.get` which was broken if the resolved address and the owner address mismatched. Which was in most cases.
And the pending anchor proposals were in need of a bit better UX and reactivity to user changes.
> Fix Org static getter method and improve pending anchors

- src/Form.svelte
- src/base/registrations/New.svelte
- src/base/registrations/Routes.svelte
- src/base/registrations/Submit.svelte
- src/base/registrations/Update.svelte
- src/base/registrations/View.svelte
- src/base/registrations/resolver.ts
- src/base/resolver/Query.svelte
- src/utils.ts
This PR allows user to open non-radicle ENS domains in registration form and also edit them.
It also fixes an issue that wasn't allowing editing ENS information, due to passing `undefined` values for empty input fields, we now cast `undefined` to an empty string.
Closes #190, #167
> Improve support for non-radicle ENS domains

- public/index.css
- scripts/test
- src/NotFound.svelte
- src/Profile.svelte
- src/SeedAddress.spec.ts
- src/anchors.ts
- src/base/orgs/Org.ts
- src/base/orgs/View/Projects.svelte
- src/base/profiles/AnchorActions.svelte
- src/base/profiles/AnchorBadge.svelte
- src/base/projects/BranchSelector.spec.ts
- src/base/projects/BranchSelector.svelte
- src/base/projects/Header.svelte
- src/base/projects/View.svelte
- src/base/projects/Widget.svelte
- src/base/seeds/Seed.ts
- src/base/seeds/View.svelte
- src/profile.ts
- src/project.ts
* Anchors are loaded alongside projects, but project listings always come from seeds now
* Removing project info loading from `Widget`
* Start unifying anchor handling
* Rename "Project*" to "Anchor*" when appropriate
* Move to new project api with embedded metadata
> Anchors refactor

- src/base/projects/Commit/CommitTeaser.svelte
This PR fixes commit teaser overflow by adding some `overflow: hidden` and some `text-overflow: ellipsis` in some needed places
Closes #188
> Fix commit teaser overflow

- src/base/orgs/View/Projects.svelte
- src/base/seeds/View.svelte
Allows to use the same `Projects` listing component for the seeds `View`.
Eventually `Projects` could turn into something too big to handle, but for now I think by managing Seeds and ETH addresses it's quite nice.
Is based on PR #192 which should be merged first.
> Use Projects listing component in seed view

- public/index.css
- src/Dropdown.svelte
- src/base/projects/BranchSelector.svelte
- src/base/projects/Header.svelte
- src/base/projects/PeerSelector.spec.ts
- src/base/projects/PeerSelector.svelte
- src/project.ts
This PR closes #203
It adds the delegate metadata obtained from the seed nodes at the route `<host>/v1/projects/<urn>/remotes`
Which has the following format
```json
[
{
"id": "hyyg555wwkkutaysg6yr67qnu5d5ji54iur3n5uzzszndh8dp7ofue",
"name": "sebastinez",
"delegate": true
}
]
```
And it shows it the following way.
If there is no metadata provided by the seed node it maintains the current format showing the peer ids without additional metadata
Also the current selected peer is being highlighted, the same applies to the branch selector which uses the same `Dropdown` component underneath.
> Add delegate info to peer selector

- src/base/projects/Blob.svelte
- src/base/projects/Browser.svelte
- src/base/projects/ProjectRoute.svelte
- src/base/projects/View.svelte
- src/project.ts
- src/utils.ts
This PR adds the ability to pass a link to a `Browser` with a location hash pointing to a specific line in the document.
For example:
`/seeds/<host>/<projectId>/tree/<peerId>/<path>#L27`
There are other places where this eventually can come handy, but for now I just add the `hash` properties to the `browserStore` and work with the `Blob` component.
I'm seeing possibilities to link to files and lines of code in a specific commit detail view..
> Add link to code line numbers

- src/Markdown.svelte
- src/base/projects/Browser.svelte
- src/base/projects/Readme.svelte
- src/utils.ts
This loads images asynchronously inside markdown documents.
> Load images in markdown documents

- src/config.json
When browsing the interface on RInkeby the landing page was not loading, due to `config.seeds.pinned` being `undefined`.
I added an empty array similar to `users` and `orgs` to allow the landing page to be loaded.
> Add empty seeds.pinned property to Rinkeby config

- cypress/fixtures/ceramicStream.json
- cypress/integration/connect.spec.ts
- package-lock.json
- package.json
The request to the Ceramic API endpoint was returning a non zero exit code in some cases, due to a uncaught `SyntaxError`
This PR adds a better fixture to the route, to reduce the flakyness.
> Reduce flakiness of E2E test suite

- src/base/projects/Issue.svelte
- src/base/projects/Issue/IssueTeaser.svelte
- src/issue.ts
> Update issue state to new serialization

- public/index.css
- src/Form.svelte
- src/Header.svelte
- src/Profile.svelte
- src/RadicleUrn.svelte
- src/Search.svelte
- src/SiweConnect.svelte
- src/base/orgs/Create.svelte
- src/base/orgs/Index.svelte
- src/base/orgs/TransferOwnership.svelte
- src/base/profiles/AnchorActions.svelte
- src/base/projects/Browser.svelte
- src/base/registrations/Index.svelte
- src/base/registrations/View.svelte
- src/base/vesting/Index.svelte
- src/components/Modal/ConnectWallet.svelte
- src/ens/DomainInput.svelte
- src/ens/SetName.svelte
- Added a variable for `--button-regular-height`
- Added a variable for `--button-small-height`
- Added a variable for `--button-tiny-height`
- Changed the badge size to be 1.5rem (height wasn't previously defined, so it was falling between 23 and 24, now it's a more crispy solid 24 height)
- rename "small" to "regular"
- rename "tiny" to "small"
- fix the grey border on the white button hover
- add new size for badges that is "tiny"
Fixes #257 
Fixes #272
Signed-off-by: Brandon Oxendine <brandon.oxendine@gmail.com>
> Unify Button heights

- src/config.ts
Changes the `No Web3 provider available` error message to `A wallet such as Metamask must be enabled on your browser.`
> Improve error message when missing web3 provider

- package-lock.json
- package.json
- src/Markdown.svelte
- src/SeedDropdown.svelte
- src/polyfills/events.ts
- vite.config.ts
This PR updates Vite to 3.0
Since Vite now removed more Node Core modules polyfills, we need to replace `sanitize-html` with `xss` which works without `postcss` and it's node dependencies.
> Update Vite to 3.0

- .github/workflows/check-build.yml
- .github/workflows/check-format.yml
- .github/workflows/check-integration-test.yml
- .github/workflows/check-unit-test.yml
- .github/workflows/check.yml
ubuntu-latest [already includes](https://github.com/actions/runner-images/blob/ubuntu20/20220807.1/images/linux/Ubuntu2004-Readme.md#language-and-runtime
) a recent node version (16.16.0).
And node 14 is at its EOL.
```
WARNING: node-v14.20.0 is in LTS Maintenance mode and nearing its end of life.
It only receives *critical* security updates, *critical* bug fixes and documentation updates.
```
This should also shave off some time from our builds.
> Don't use outdated node on CI

- package.json
When running unit tests locally, some of them fail with:
```
❯ src/utils.test.ts:5:14199
- Expected   "Sat, 01 Jan 2022 12:00:00 GMT"
+ Received   "Sat, 01 Jan 2022 11:00:00 GMT"
❯ src/utils.test.ts:5:14199
- Expected   "Sat, 05 Mar 2022 12:00:00 GMT"
+ Received   "Sat, 05 Mar 2022 11:00:00 GMT"
```
We set the timezone explicitly before running the tests, to prevent timezone sensitive tests from failing.
> Always use the same timezone when running unit tests

- src/components/Modal/ConnectWallet.svelte
- Removes WalletConnect-compatible wallet link, which is not reliable.
- Adds a generic text to let people know, they should use a WalletConnect-compatible wallet.
Closes #299
> Remove WalletConnect compatible link

- cypress/e2e/project.spec.ts
- src/Dropdown.svelte
- src/Floating.svelte
- src/Header.svelte
- src/SeedDropdown.svelte
- src/base/projects/BranchSelector.spec.ts
- src/base/projects/BranchSelector.svelte
- src/base/projects/CloneButton.svelte
- src/base/projects/Header.svelte
- src/base/projects/Patch/PatchTabBar.svelte
- src/base/projects/PeerSelector.spec.ts
- src/base/projects/PeerSelector.svelte
Decouple global modal state from the parent element by moving it into a module store of the modal itself.
This makes the floating modal component more composable, we don't have to track the modal state in the parent component anymore. This means we can just add as many floating modals to a page as we like and only one of them will stay open at a time.
This change also implements hiding any open modals when clicking outside of the modal.
https://user-images.githubusercontent.com/158411/183942984-3f6cc541-4290-41cd-8bbf-8e4bb5852049.mov
> Refactor project header modals

- cypress/support/e2e.ts
- src/Comment.svelte
- src/base/registrations/registrar.ts
- src/base/vesting/state.ts
- src/config.ts
- src/session.ts
I think debug logs should be logged with the appropriate log level, so they don't mix in with other stuff that's going on in the console.
They're still accessible via:
> Hide debug logs

- index.html
This gets rid of these:
⚠️ A preload for 'https://app.radicle.network/fonts/Inter-Regular.woff' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
> Get rid of crossorigin warnings in console

- src/base/projects/Commit/CommitTeaser.svelte
- src/base/projects/Project.svelte
- src/base/projects/SourceBrowser/FileDiff.svelte
This PR adds a `<Loading>` indicator to the project view to show the user that something is happening.
Adds `View file` next to the browse icon in the `CommitTeaser`, `Changeset` and `FileDiff` components
Closes #268 
Closes #267
> Add project detail loader and `View file` tooltip

- src/base/registrations/View.svelte
This PR closes #262 
It removes the `Transfer` button, since the functionality hasn't been implemented.
Adds a `title` property to the `Edit` button to explain that one must be the owner of the profile to make edits.
> Improve Profile Edit and Transfer buttons

- src/config.ts
Currently when running the app locally we require the user to have Metamask installed.
We could rely on the Infura Id used by Ethers to have a provider for when `import.meta.env.DEV === true`.
This would improve the UX for users wanting to use the interface on localhost.
> Use ethers defaultProvider when in development mode

- src/Markdown.svelte
> Skip absolute image URLs for getImage in Markdown.svelte

- src/utils.ts
This gets rid of the warning we are seeing in the console.
```
TTL caching without ttlAutopurge, max, or maxSize can result in unbounded memory consumption. UnboundedCacheWarning LRU_CACHE_UNBOUNDED
```
> Add missing `max` attribute to cache call

- src/Dropdown.svelte
This fixes a regression introduced in https://github.com/radicle-dev/radicle-interface/pull/345.
vs
> Fix badge alignment in dropdown

- src/Loading.svelte
This prevents from loading indicators flickering for a split second during a page draw. For requests that take longer than 200ms we show the loading animation.
Before:
https://user-images.githubusercontent.com/158411/188100584-482797a9-ceb2-4a5e-95aa-05a4ac057959.mov
After:
https://user-images.githubusercontent.com/158411/188100630-7d2a2e40-0799-482d-81b1-c976951778e5.mov
> Show loading indicators after a delay

- src/utils.ts
Fixes a regex error, since I only used a character set and not a group the return value of `.exec(src)` is not the one we needed..
> Fix emoji parser

- src/Card.svelte
- src/List.svelte
- src/Profile.svelte
- src/base/orgs/View/Projects.svelte
- src/base/projects/History.svelte
- src/base/projects/Project.svelte
- src/base/seeds/Seed.ts
- src/base/seeds/View.svelte
- src/commit.ts
- src/project.ts
Adds a `More` button on the end of the commits history, and when clicked loads more commits
This PR depends on the merge and implementation of https://github.com/radicle-dev/radicle-client-services/pull/181
Since this would allow us to check if there are more commits to be loaded or if we are already at the end
> Enable loading more items in commit history and project listing

- public/index.css
- src/Markdown.svelte
- src/base/vesting/Index.svelte
- inline the styles where appropriate
- style markdown tables properly
- this also fixes a heading spacing issue
Refs: https://github.com/radicle-dev/radicle-interface/issues/373.
> Remove global table styling

- src/Markdown.svelte
It breaks long hard-wrapped paragraphs in our RIPs.
vs 
This will break the default GitHub cheat-sheet TOC though:
> Undo markdown hard-wrapping

- src/config.ts
Instead of going first for Alchemy in production, try to use Metamask if available, to reduce load on Alchemy and also give users the chance to use their own jsonrpc endpoint.
> Use Metamask as provider before trying to use Alchemy

- src/Markdown.svelte
- src/base/projects/Blob.svelte
- src/base/seeds/View.svelte
- remove space between `path` and `filename` in Blob.svelte
- remove top margin from the first element in markdown docs
- fix Seed ID alignment on seed page
Closes: https://github.com/radicle-dev/radicle-interface/issues/389
> Fix small alignment issues

- src/Markdown.svelte
Refs https://github.com/radicle-dev/radicle-interface/issues/373.
Fixes:
- image titles
- inline code block background
- H6 size and color
- format blockquotes
- `<hr />` tag spacing
- style definition lists
> Make sure commonly used markdown renders nicely

- src/base/projects/Patch.svelte
This fixes a visual regression.
Left is proposed:
> Show commit SHA below patch title

- src/base/projects/Widget.svelte
- src/config.json
Show "No description" when the project description is missing.
> @joelhans: Also I saw that you added astrolabe to the homepage, which is very exciting because that's my project(!), but I really messed that repo up and ended up moving to the willow seed node instead, so maybe we switch the link to point there instead? https://app.radicle.network/seeds/willow.radicle.garden/rad:git:hnrkrwewct7pb1biwmf59qa3rzod8mauundzy
> Improve pinned projects

- src/base/orgs/Org.ts
- src/utils.ts
We had to rewrite `querySubgraphWithRetry` due to flaws in the return value logic and how the recursion took place.
> Gracefully handle API quota exhaustion

- src/config.json
- src/config.ts
Instead of defining the seeds in relation to the current network we should be able to query them agnostic to the current connected network
This fixes issues with different search results depending on the connected network
> Move `seeds.pinned` out of network scope

- src/utils.ts
We were calling `return query?.safe !== null ? true : false` but since `query` can become `undefined` through the optional chaining operator, we were returning `true` if the query wasn't able to retrieve anything.
> Fix `isSafe` util function

- src/resolver.ts
Since ENS names go through a UTS46 normalisation process case-folds labels before hashing them.
So we shouldn't be ENS querying uppercase names.
> Lowercase ENS name search query

- src/Form.svelte
The form didn't close when pressing the "Cancel" button. This regression was introduced in b8e7239ba4b2919dd6aee4f0e7e6874c1416cbd7.
https://user-images.githubusercontent.com/158411/192533574-77480aac-c60d-4720-b1c4-17476050fe7f.mov
> Exit editable form state when pressing "Cancel"

- cypress/e2e/projectCommits.spec.ts
- src/base/projects/Commit/CommitAuthorship.svelte
- src/base/projects/Commit/CommitTeaser.svelte
- src/base/projects/Commit/CommitVerifiedBadge.svelte
- Shows a delegate `Badge` in `CommitAuthorship` if available.
- Changes `width: 14rem` to `min-width: 14rem` to allow space for horizontal text without the need of wrapping it.
e.g. <Avatar> cloudhead [delegate] committed already was in need of being wrapped which doesn't look nice.
Closes #404
> Show delegate badge in commits

- src/Search.svelte
It would close the context menu before you can see the shake animation.
https://user-images.githubusercontent.com/158411/193039020-40068070-750e-44ed-b51e-92fa014cb4e2.mov
> Leave mobile search context menu open if search fails

- src/config.json
Fixes:
```
Access to fetch at 'https://seed.alt-clients.radicle.xyz:8777/v1/projects/rad:git:hnrkmg77m8tfzj4gi4pa4mbhgysfgzwntjpao' from origin 'https://app.radicle.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
seed.alt-clients.radicle.xyz:8777/v1/projects/rad:git:hnrkmg77m8tfzj4gi4pa4mbhgysfgzwntjpao:1          Failed to load resource: net::ERR_FAILED
app.radicle.xyz/:1 Access to fetch at 'https://seed.alt-clients.radicle.xyz:8777/v1/projects/rad:git:hnrkjajuucc6zp5eknt3s9xykqsrus44cjimy' from origin 'https://app.radicle.xyz' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is …
```
> Use new clients.radicle.xyz domain for some pinned projects

- .gitignore
- index.html
- package-lock.json
- package.json
- scripts/copy-katex-assets
- src/Markdown.svelte
- src/utils.ts
This PR:
- adds a marked extension that parses Katex expressions, and renders them using [katex](https://katex.org/).
- to be able to do so it adds also a stylesheet provided by katex.org
- also changes the markdown sanitizer from `xss` to `dompurify` for saner defaults and MathML support.
Here you can see the difference:
**Before**
**After**
Closes #413
> Add katex render to Markdown

- src/Async.svelte
- src/List.svelte
- src/Profile.svelte
- src/base/seeds/Seed.ts
- src/base/seeds/View.svelte
- src/base/seeds/View/Projects.svelte
- Fetches project count information from `/stats` http-api endpoint
- If less projects are shown than the project count, show a `More` button
- If the amount of projects shown is equal to the total amount stop showing it.
- If the seed does not support the `/stats` endpoint the button will shown until we're not able to fetch more projects.
> Show fetch more button only when more projects are available

- src/Header.svelte
- src/base/faucet/Index.svelte
- src/base/registrations/Index.svelte
- src/base/registrations/Submit.svelte
- src/config.json
- src/config.ts
- src/utils.test.ts
- src/utils.ts
Closes https://github.com/radicle-dev/radicle-interface/issues/438.
TBD:
> Replace Rinkeby testnet with Goerli

- package-lock.json
- package.json
- src/Address.svelte
- src/Form.svelte
- src/base/projects/CloneButton.svelte
This time we don't upgrade the transitive dependencies. Checked the production build locally, it works.
Seems like the `sive-parser` upgrade caused the production breakage. We should add a [smoke check](https://github.com/radicle-dev/radicle-interface/issues/456).
> Upgrade dependencies

- src/Markdown.svelte
We expect the `Markdown` component to receive a `content: string`, but we also check if `content` is truthy before rendering anything, and this can get messy when `content` is an empty string.
Fixed by removing the truthy check for `content`.
Closes #465 
> Handle empty string in `Markdown` component

- src/Address.svelte
- src/SeedAddress.spec.ts
- src/SeedAddress.svelte
- src/base/projects/Header.svelte
- src/base/seeds/Routes.svelte
- src/base/seeds/Seed.ts
- src/base/seeds/View.svelte
- src/base/seeds/View/Projects.svelte
- src/project.ts
Fixes broken `gip-editors` profile.
They had set the [ENS records](https://app.ens.domains/name/gip-editors.radicle.eth/details) correctly, but they weren't picked up correctly by the UI.
> eth.radicle.seed.api: https://api.radicle.thegraph.com:443
> eth.radicle.seed.git: https://git.radicle.thegraph.com:443
This should now work via both the profile or the seed page:
- http://127.0.0.1:3000/gip-editors.radicle.eth/rad:git:hnrkxgekdi5gikjcqru4swpm1kfrhqqry7qto/tree/8c62a29ddc6c4d3c9322209bcd59ce5a55f2a0e3
- http://127.0.0.1:3000/seeds/api.radicle.thegraph.com:443/rad:git:hnrkxgekdi5gikjcqru4swpm1kfrhqqry7qto/tree/8c62a29ddc6c4d3c9322209bcd59ce5a55f2a0e3
https://user-images.githubusercontent.com/158411/197223189-a356098c-740f-4edd-9c5e-b784b0250d2d.mov
> Correctly detect custom HTTP API ports

- src/base/projects/View.svelte
By passing a too broad scope into the `getProject` function in the  project view we are re-rendering everything always
This PR reduces the scope to the required `urn`, `seed`, `profile` and `peer` information
https://user-images.githubusercontent.com/7912302/200275163-c3684aa4-0b9a-4307-856c-d268e08a2ee1.mov
> Avoid the re-rendering of the ProjectMeta component

- cypress/e2e/projectHeader.spec.ts
- src/base/projects/Blob.svelte
- src/base/projects/Browser.svelte
- src/base/projects/Header.svelte
- src/base/projects/HeaderToggleLabel.svelte
- src/base/projects/Readme.svelte
- src/base/projects/Stat.svelte
This PR adds a toggle button on the top right of the file preview shown in the Browser.
This allows to see the markdown file in its raw format and also reference a specific line of the file by URL.
It also refactors the project header stats into their own component `Stat.svelte`
Closes #423
> Allow switch between rendered markdown and raw content

- .github/workflows/check-build.yml
This PR extends the build CI pipeline, to assert that the production build created by `npm run build`  and served by `npm run serve`, passes through the `home.spec.test` e2e test.
Closes #456
> Add smoke check for production builds

- src/Markdown.svelte
Current design with `line-height: 1.5`
New `line-height: 1.625`
Closes #459
> Add `line-height: 1.625` to `li` and `ol` elements

- src/base/projects/Blob.svelte
With the addition of the new `Raw` button there came some responsiveness issues this PR should take care of.
> Improve display of lastCommit in Blob component

- src/utils.ts
Twemojis were imported with an absolute base, we need to listen to `window.hashRouting` and switch to a relative base if we use hash routing
> Fix twemoji base

- src/router/index.ts
Ok no idea how this one passed the review..
We were using `window.history.replaceState` in the `router.push` fn instead of `window.history.pushState`
> Push new routes to the history stack instead of replacing it

- vite.config.ts
We split some third party packages into their own bundles to reduce the size of the index.js bundle.
We also don't need hmr ever in production.
Also removes the sourcemap output in build to reduce the size of the total bundle.
In dev environment we still get an inlined sourcemap, to help debugging.
Improves the speed also a bit, "about 200ms locally hosted" since we don't have to wait for e.g. markdown, siwe, walletconnect packages for a first contentful paint, since they have a considerable size
> Removes `compilerOptions.dev` and chunk size warnings on build

- src/base/projects/Blob.svelte
There are repos that have files with a missing new final line aka the last line hasn't a line break `\n` at the end of the file.
So we weren't counting that last line.
To avoid this missing line we should add 1 to the amount of lines in that case.
This should be probably something solved on the backend once we get more information on the source code..
> Check if there is a final new line in the blob content

- package.json
- scripts/copy-katex-assets
Since Netlify has issues with triggering the `postinstall` script.
We should be able to trigger the postinstall scripts during the build step, so we don't miss it.
> Add postinstall scripts to build step

- src/base/vesting/vesting.ts
It's a typo, while cleaning up config
> Fix ABI used in vesting page

- src/base/projects/View.svelte
- src/router/index.ts
- tests/e2e/landingPage.spec.ts
- tests/e2e/router.hash.spec.ts
- tests/e2e/router.history.spec.ts
- tests/e2e/seed.spec.ts
- tests/support/router.ts
- vite.config.ts
This PR is based on top of the `rudolfs/playwright` PR.
It removes some navigation testing from the original PR and adds support for testing hash route navigation.
Fixes also some found bugs that started showing in particular on the hash routing.
With future PRs I'll be adding more tests for the router but I think its a nice start.
Creates a conditional vite config, to allow the testing of the hash router, we want to avoid that vite overwrites `window.HASH_ROUTING` with the `define` section in the vite config
> Add e2e tests for router

- src/App.svelte
- src/base/vesting/Form.svelte
- src/base/vesting/Routes.svelte
- src/base/vesting/View.svelte
- src/base/vesting/vesting.ts
- src/router/definitions.ts
- src/router/index.ts
- tests/unit/router.test.ts
This allows people to either search for their vesting contract through the search form or visit directly `vesting/<contract address>`
Was not able to test withdraw functionality, but this PR does not touch it, so should be fine.
Small example on the functionality
https://user-images.githubusercontent.com/7912302/203993327-8d2d0e8b-da1a-4001-97dc-945045cb6368.mov
> Add route support to vesting feature

- .github/workflows/check-e2e.yml
Running `npx playwright install --with-deps`
Running `npx playwright install-deps`
> Cache playwright binaries

- .github/workflows/check-build.yml
- .github/workflows/check-e2e.yml
- .github/workflows/check-format.yml
- .github/workflows/check-unit-test.yml
- .github/workflows/check.yml
This PR changes the event triggers for the GitHub CI to
```
on:
push:
branches:
- master
pull_request:
branches:
- master
```
This changes the behaviour to only run the checks when either a push is being made to the `master` branch or updates to a pull_request but not both
Closes #517
> Run GitHub CI only if push against master or push to PR but not both

- .github/workflows/check-build.yml
- .github/workflows/check-e2e.yml
- .gitignore
- playwright.buildSmoke.config.ts
- playwright.config.ts
- tests/build/smoke.spec.ts
- tests/e2e/hashRouter.spec.ts
- tests/e2e/historyRouter.spec.ts
- tests/e2e/landingPage.spec.ts
- tests/e2e/project.spec.ts
- tests/e2e/project/commit.spec.ts
- tests/e2e/project/commits.spec.ts
- tests/e2e/settings.spec.ts
- tests/support/fixtures.ts
- tests/visual/landingPage.spec.ts
- tests/visual/project.spec.ts
- tests/visual/seed.spec.ts
We abuse the Github cache action to store generated snapshots when pushing to master and then load them in pull requests and run the visual tests against it. This way we don't have to commit the images to the repository and always get visual diffs against the latest master.
Here's how the proposed workflow could look like:
- When this check fails, it means that there are visual differences in the proposed pull request.
- In this case the reviewer has to download the artifacts and check that the visual changes are not regressions, but intentional changes.
- In this case it seems like there is a visual regression that was not intended:
- We ask the PR author to fix the problem
- Author fixes the issue, pushes the changes and the check passes
- We merge to master and the snapshots …
> Add visual snapshot tests

- .github/workflows/check-build.yml
- .github/workflows/check-e2e.yml
- .github/workflows/check-format.yml
- .github/workflows/check-unit-test.yml
- .github/workflows/check.yml
- playwright.config.ts
CI seems to take longer for the big markdown screenshot diff (usually around 22s).
Ignore warnings about there being no artifacts to upload.
> Small CI improvements

- src/Markdown.svelte
This PR closes #540 
It filters out any `Object.entries` that are either `string` or `number`
> Skip objects in front-matter

- .gitignore
- tests/e2e/project/commit.spec.ts
- tests/e2e/project/commits.spec.ts
- tests/visual/landingPage.spec.ts
- tests/visual/project.spec.ts
- tests/visual/seed.spec.ts
Forgot to mock time in some places. Some tests would run too fast locally and the snapshots would end up showing a loading state, hence the added `{ waitUntil: "networkidle" }`.
> Fix flaky visual tests

- .github/workflows/check-e2e.yml
The cache didn't get updated when pushing to master because it was always a cache hit.
> Clean up snapshot cache on master

- src/components/Authorship.svelte
- src/lib/diff.ts
- src/lib/issue.ts
- src/lib/patch.ts
- src/lib/project.ts
- src/views/projects/Issue.svelte
- src/views/projects/Patch/PatchTimeline.svelte
To reduce the scope of #515.
The legacy seeds don't have any working issues, so I didn't bother to write any translation.
This fixes patch browsing, there was a regression.
Test it against: http://127.0.0.1:3000/seeds/clients.radicle.xyz/rad:git:hnrkq5sti58yw41szighu565oprgt5eduhmhy/patches/hnrkkktb1dyt9gkuufzuax1uzdoueiskxzrto
> Rename issue/patch APIs

- src/components/Markdown.svelte
It looks like there was maybe a regression at some point (I guess [here](https://github.com/radicle-dev/radicle-interface/commit/569b6601341af8cd9fb31232bf6bde4ecd1c8a25)) and we lost the colors on the code and blockquote blocks. This adds them back. We also give blockquotes some padding like regular paragraphs.
Edit: how can I fix the visual test failure?
> Fix a couple of markdown styles

- .github/workflows/check-e2e.yml
- tests/visual/markdown.spec.ts
- tests/visual/project.spec.ts
Before we had a single very long screenshot, that was hard to compare. Now we have a screenshot per section, which should make it easier to spot differences.
For example:
> Split up visual markdown specs into sections

- .github/workflows/check-build.yml
- .github/workflows/check-e2e.yml
- src/global.d.ts
- src/index.ts
- src/lib/e2eTestStubs.ts
Current working theory: the dynamic import made the timer stubs load in the wrong order sometimes.
Not a 100% sure tho. 🤷 
This also removes the playwright deps install steps from the jobs. Apparently the tests work just fine without them. Saves us some build time.
> Fix flaky visual landing page spec

- src/views/projects/ProjectMeta.svelte
Replaces all URLs in project descriptions into clickable anchor tags.
Closes #458
> Convert URLs in project descriptions to anchor tags

- .github/workflows/check-e2e.yml
- scripts/run-httpd-with-fixtures
~~Demonstrates how to obtain `radicle-httpd` binary for e2e tests.~~
Uses a statically linked `radicle-httpd` executable to run e2e tests in CI (i.e. no Docker).
> Download radicle-httpd executable for e2e tests

- src/lib/registrar.ts
We were destructuring an array of promises into individual values, but we forgot to add `seedGit` as a new value, this gave issues for the creation of a new `EnsProfile`.
This PR originated by #584 
> Add `seedGit` to `getRegistration` destructuring

- src/lib/ethereum/networks/goerli.json
ENS has deployed on the 20th of September 2022 new contracts which can be seen here.
https://discuss.ens.domains/t/namewrapper-updates-including-testnet-deployment-addresses/14505
This commit updates the ReverseRegistrar contract which allow users to create their reverse records again
> Update the ReverseRegistrar contract address.

- .github/workflows/check-e2e.yml
There was a problem with permissions introduced in https://github.com/radicle-dev/radicle-interface/pull/577.
```
Deleting Linux-snapshots cache
Error: Resource not accessible by integration
Done
```
> Fix clearing snapshot cache

- src/App.svelte
- src/lib/router.ts
- src/lib/router/definitions.ts
- src/views/session/Index.svelte
This PR adds a session route with the following spec
```
/session/<sessionId>&sig=<Signature>&pk=<PublicKey>
```
This route gets shown in the cli when `rad web` is called to authenticate the web client with the httpd.
Once the web client lands on this route it sends the session id, signature and public key to the httpd to authenticate the session, and then stores the authenticated session id in the sessionStorage to keep persistance between page reloads.
> Add httpd session route

- src/components/Markdown.svelte
- src/lib/markdown.ts
- src/lib/utils.ts
- tests/unit/utils.test.ts
This PR adds support for footnotes in markdown.
It does so by adding two more markdown extensions:
- One for the inline footnote reference.
- And the other for the footnotes at the end of the document.
~~There is still some work left, I would like to wrap the footnotes at the end of the document inside some `<section>` to get a specific styling applied.
Also there are some edge cases I would like to fix.~~
This can be revisited in a different PR if needed, for now this solves the issue at hand.
This PR will eventually close #575
> Add footnotes support to markdown

- .github/workflows/check-e2e.yml
- scripts/run-httpd-with-fixtures
```
$ ./scripts/run-httpd-with-fixtures --download --non-interactive
Downloading radicle-httpd
Unpacking fixture /Users/rudolfs/work/radicle-interface/tests/fixtures/seeds/palm-heartwood.tar.bz2
Starting radicle-httpd-a5811e4
RAD_HOME=/Users/rudolfs/work/radicle-interface/tests/tmp/palm RAD_PASSPHRASE=asdf radicle-httpd-a5811e4
2023-01-31T15:48:57.833117Z  INFO radicle_httpd: version 0.1.0-a5811e4
2023-01-31T15:48:57.836700Z  INFO radicle_httpd: git version 2.39.0
2023-01-31T15:48:57.837572Z  INFO radicle_httpd: using radicle home at /Users/rudolfs/work/radicle-interface/tests/tmp/palm
2023-01-31T15:48:57.838592Z  INFO radicle_httpd: listening on http://0.0.0.0:8080
```
If no option is specified, we use the `radicle-httpd` binary that is in `PATH`.
Downloaded binaries are cached so we …
> Use radicle-httpd from our public download location

- tests/e2e/clipboard.spec.ts
- tests/e2e/project.spec.ts
- tests/e2e/settings.spec.ts
Some of our specs were flaky because we forgot to `await` in certain places.
> Fix flaky specs

- src/views/projects/Commit/CommitTeaser.svelte
- src/views/projects/History.svelte
- tests/e2e/project/commits.spec.ts
This PR fixes a design regression in the `CommitTeaser`.
Also reduces a nesting level of the `CommitTeaser` component in the `History` view
> Fix rounded corners in CommitTeaser

- playwright.config.ts
The threshold is expressed a percentage, so on full-page screenshots it depends on how big the entire screenshot is. We want to catch smaller changes. The threshold was too high to catch the rounded corners change in a full-page screenshot.
> Lower image diff threshold

- src/App/Header.svelte
- src/App/Header/Search.svelte
Also don't show the connect button in the mobile layout. We don't support running nodes on mobile anyway.
On desktop still expand and contract the search bar depending on focus.
Mobile:
Desktop:
> Don't expand search bar on mobile

- src/App/Header/Search.svelte
- src/components/Floating.svelte
- search icon alignment
- clicking outside a dropdown now closes it properly
https://user-images.githubusercontent.com/158411/218795989-58641f60-c909-4ac0-845a-ecf0e222b7e6.MP4
> Safari and mobile Safari tweaks

- src/config.json
clients.radicle.xyz got migrated to Heartwood. Removed pax to have an even number of projects and they align in two rows.
> Clean up pinned projects

- README.md
We deployed the app at https://github.com/radicle-dev/radicle-interface/commit/7a3244b43c909a6cd272166363cf126c0292a7c1 with an informative message that's always present in the header on IPFS. This allows users to access the old pre-heartwood seeds if they want by running an IPFS node locally (via the IPFS desktop app).
Rendered [README.md](https://github.com/radicle-dev/radicle-interface/blob/466f72002fc9bf21f90dab98cfa71130a3d2c4c6/README.md).
Closes https://github.com/radicle-dev/radicle-interface/issues/616.
> Document legacy IPFS deployment

- .github/workflows/check-e2e.yml
- .github/workflows/check-visual.yml
Splits out the visual diffs into a separate workflow and adds a Github bot that adds a comment about the visual diff status. It edits the existing comment if there is one.
> Always pass diff step and show the status as a comment

- .github/workflows/check-visual.yml
Hardcoded the link by accident.
> Fix link to artifacts

- src/views/projects/Commit.svelte
- src/views/projects/SourceBrowser/FileDiff.svelte
Currently we didn't wrap the commit header description, and also the changesets had no wrapping in them.
So this forces the wrapping, which at least for diffs isn't the nicest wrapping, but it beats, horizontal scrolling on a mobile device..
Closes #623
> Make commit header and diff wrapping more similar to GH

- .github/workflows/check-visual.yml
Turns out we weren't regenerating visual diffs on master due to a [syntax error](https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow).
This should fix [it](https://github.com/radicle-dev/radicle-interface/actions/runs/4414906666).
```
[check-visual: .github#L1](https://github.com/radicle-dev/radicle-interface/commit/09ceeed136ce3d1599f9394914327e95b283a8bb#annotation_9671073271)
Error when evaluating 'concurrency' for job 'generate-visual-diffs'. .github/workflows/check-visual.yml (Line: 13, Col: 14): Unexpected type of value '', expected type: String.
```
> Make sure visual diffs are generated on master

- src/views/session/Index.svelte
In most cases the user will want to interact with the local seed, so it makes sense to show that page. If the auth is unsuccessful, we go to the home screen.
> Show local seed page upon successful authentication

- src/lib/patch.ts
- src/lib/project.ts
- src/views/projects/Header.svelte
- src/views/projects/Patch.svelte
- src/views/projects/Patch/PatchTeaser.svelte
- src/views/projects/Patches.svelte
- src/views/projects/View.svelte
- Changes the patch state from `proposed` to `open`
- Adds the `TabBar` back to patches
This will be needed once the heartwood PR https://github.com/radicle-dev/heartwood/pull/499 gets merged
> Update patch state from proposed to open

- .github/workflows/check-e2e.yml
- package.json
- playwright.config.ts
- playwright.ipfs.config.ts
- src/App.svelte
- src/env.d.ts
- src/global.d.ts
- src/lib/router.ts
- tests/e2e/hashRouter.spec.ts
- vite.config.ts
Some work done on seeing how we can handle env variables in Svelte/Vite/Playwright to be able to build the web app with hash router
- Moves `HASH_ROUTING` from being a vite constant which is statically replaced during build and else put on the `window` object, to the `import.meta.env` object, which also get replaced by Vite during build.
- Separates Playwright into history router config and hash router config to be able to handle them on a config level instead of inside the hashRouter test
> Fix hash router build and test configuration

- src/lib/pluralize.ts
- src/views/projects/Header.svelte
- src/views/projects/SourceBrowser/Changeset.svelte
- tests/e2e/project.spec.ts
- tests/e2e/project/commit.spec.ts
Ok I think this is a nice way of doing it without using a library, and with a nice function signature.
Closes #650
> Pluralize values instead of parenthesis

- src/lib/project.ts
- src/views/projects/Patches.svelte
To avoid showing `undefined <patch state>` fallback to 0 and disable it
> Patch states fallback to disable and show default if undefined

- .eslintrc.json
- tests/e2e/project.spec.ts
- tests/support/globalSetup.ts
- tsconfig.json
This will help us catch forgotten `await`s and let's us avoid nasty race conditions.
The only drawback is that it's slower:
Without the rule:
```
./scripts/check  15.52s user 1.06s system 188% cpu 8.817 total
```
With the rule:
```
./scripts/check  26.91s user 3.14s system 184% cpu 16.307 total
```
> Enable the @typescript-eslint/no-floating-promises rule

- public/layout.css
- src/components/Authorship.svelte
- src/components/Comment.svelte
- src/components/Dropdown.svelte
- src/components/Markdown.svelte
- src/lib/utils.ts
- src/views/projects/Blob.svelte
- src/views/projects/Cob/AssigneeInput.svelte
- src/views/projects/Cob/CobHeader.svelte
- src/views/projects/Cob/CobStateButton.svelte
- src/views/projects/Cob/TagInput.svelte
- src/views/projects/Commit.svelte
- src/views/projects/Commit/CommitAuthorship.svelte
- src/views/projects/Issue.svelte
- src/views/projects/Issue/IssueTeaser.svelte
- src/views/projects/Patch.svelte
- src/views/projects/Patch/PatchTeaser.svelte
- src/views/projects/PeerSelector.svelte
- src/views/projects/SourceBrowser/FileDiff.svelte
This PR closes #666, #669, #670
See commits for changeset
I also removed the fork icon once a peer is selected, I don't think it helps and it doesn't look good together with the blockie
- Reduced formatted object ids to 7 instead of 11 digits
> Fix small UI issues

- src/components/Markdown.svelte
- src/lib/markdown.ts
This PR should close #682, #645
It adds a `.file-link` class to eventual relative file links inside markdowns that also aren't hash anchor links.
Then we are able in the `Markdown` component to query those elements and call `updateProjectRoute` with the new path
This is something I would like to write a e2e test about.. But I'll wait for CLI tooling, since it needs changes to the seed fixture and I think that can wait.
> Fix relative markdown file links

- src/views/projects/Blob.svelte
Removes the padding from the `td` parent, and gives it to the clickable anchor tag.
Closes #692
> Improve click behaviour code highlighting

- httpd-client/lib/project.ts
- src/views/projects/Issues.svelte
- src/views/projects/Patches.svelte
- src/views/projects/View.svelte
Currently we don't query by state, which means we get patches of different states and by paginating them we eventually loose patches that should be shown by selecting their state.
Created a patch on heartwood for the `radicle-httpd` part with id `2aaaf04d2c1335b0db41f7d401d18de6d29292a6` but isn't being replicated yet on seed.radicle.xyz.
> Fetch cobs by selected or default state

- src/views/projects/Commit/CommitTeaser.svelte
- src/views/projects/Issue/IssueTeaser.svelte
- src/views/projects/Patch/PatchTeaser.svelte
Closes: https://github.com/radicle-dev/radicle-interface/issues/718.
> Use underline for commit/issue/patch teaser links

- tsconfig.json
This PR fixes #732, with adding the `noUnusedLocals` and `noUnusedParameters` option to `tsconfig`
It seems that once we added the `--tsconfig` param to `svelte-check` in f215f9f4fd54587fa0e5ba21f1289314e6e2a954 we overrode some defaults which included the checking for unused local variables.
So I added some checks to tsconfig
> Add `noUnusedLocals` and `noUnusedParameters` to `tsconfig`

- package-lock.json
- package.json
- src/components/InlineMarkdown.svelte
- src/components/Markdown.svelte
- src/lib/markdown.ts
Disables some of the deprecated options to avoid the console warnings.
Removes obfuscation of plain-text emails.
Closes #731
> Update marked to v5.0

- httpd-client/index.ts
- httpd-client/lib/project.ts
- httpd-client/lib/project/patch.ts
- scripts/run-httpd-with-fixtures
- src/components/Authorship.svelte
- src/components/Comment.svelte
- src/components/Dropdown.svelte
- src/components/ErrorMessage.svelte
- src/components/InlineMarkdown.svelte
- src/components/Markdown.svelte
- src/components/TextInput.svelte
- src/components/Thread.svelte
- src/views/projects/Cob/AssigneeInput.svelte
- src/views/projects/Cob/CobHeader.svelte
- src/views/projects/Cob/Revision.svelte
- src/views/projects/Cob/TagInput.svelte
- src/views/projects/Commit/CommitTeaser.svelte
- src/views/projects/Issue.svelte
- src/views/projects/Issue/New.svelte
- src/views/projects/Patch.svelte
- src/views/projects/View.svelte
- tests/e2e/project.spec.ts
- tests/e2e/project/commits.spec.ts
Ok this PR tackles a few design issues
With revision independent activity timeline, and some items have moved into and out of the patch header, like description, revision selector.
Also added commits to patch activity timeline.
This PR closes #667 #693
> Improve patch timeline and add description

- httpd-client/index.ts
- httpd-client/lib/fetcher.ts
This fixes the request to not add the additional `/` which broke the seeds view https://app.radicle.xyz/seeds/seed.radicle.xyz.
We were querying `https://seed.radicle.xyz/api/v1/` instead of `https://seed.radicle.xyz/api/v1`. The previous backend version was happily accepting this, but that broke recently. I don't know why it broke now.
> Fix httpd client root query

- src/views/projects/SourceBrowser/FileDiff.svelte
Closes https://github.com/radicle-dev/radicle-interface/issues/266.
With this change:
Without this change:
Github for reference:
> Make diff line background uniform across gutter and body

- src/views/projects/Patch/PatchTeaser.svelte
It will show either "Opened x days ago" or "Updated x days ago" depending whether there is one or multiple revisions.
Closes https://github.com/radicle-dev/radicle-interface/issues/752.
> Adjust action wording to show only latest action in patch list

- src/views/projects/Issue.svelte
Previously treated the issue body as a comment and people could post a thread reply to that first comment. Now we treat the first comment as the issue body and disallow replying to it via a thread. There are still some old replies, we show them as regular comments.
Closes https://github.com/radicle-dev/radicle-interface/issues/749.
http://localhost:3000/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/issues/923cce20c2a7e6629f5c3ace6127d8a77578901d
> Show comments that are thread replies to the issue body

- src/views/projects/Commit.svelte
- src/views/projects/Commit/CommitTeaser.svelte
- src/views/projects/SourceBrowser/FileDiff.svelte
We style the commit teaser and commit header visually to fit in better with patches and issues. This means:
- commit header gets a border instead of a background color
- commit list teaser gets a background color in light mode
- file diff also gets a background color in light mode
Closes https://github.com/radicle-dev/radicle-interface/issues/721.
> Make commit list and commit view visually consistent

- src/components/SquareButton.svelte
- src/views/projects/Patches.svelte
We make sure that the space between the counter and wording doesn't wrap and then wrap the tabs themselves if they take more space than the viewport.
Closes: https://github.com/radicle-dev/radicle-interface/issues/665, https://github.com/radicle-dev/radicle-interface/issues/720
> Make sure filter tabs are displayed properly on mobile

- src/views/projects/SourceBrowser/FileDiff.svelte
Before:
After:
Github for reference:
> Don't select the + and - signs when selecting a diff

- src/lib/markdown.ts
This PR closes #765
Due to possible casing mismatches in how an inline link is written and or heading ids are generated, navigation bugs can happen.
This PR lowercases all heading and inline link ids, to prevent it.
> Fix anchor hash navigation

- src/views/projects/Blob.svelte
- tests/e2e/project.spec.ts
Changes the functionality of the `Raw` button to navigate to the file.
Adding a button that toggles between the markdown and plain text and shows this by either displaying `Markdown` or `Plain`
Closes #714
> Navigate to raw file

- src/components/Markdown.svelte
- src/lib/markdown.ts
Ok it seems I introduced a regression with #643 that now impacts in list items with soft line breaks.
So I changed the implementation removing that renderer and keep the padding as it was and just removing margin when there is only a paragraph without other elements.
> Fix padding and linebreaks in markdown

- CONTRIBUTING.md
- README.md
- httpd-client/vite.config.ts
- tsconfig.json
- vite.config.ts
- Removes the IPFS deployment part from README.md.
- Updates some parts of the CONTRIBUTING.md file.
- Run `npm run check` instead of `npx eslint .`
- Make sure to sign all the commits with a pub key.
- Run all the test suites.
- Remove `svelte` and `vitest` from `types` property in `tsconfig`.
(The only type we truly need to specify there currently is `vite/client`.
> Update some markdown files and tsconfig

- src/components/Dropdown.svelte
- src/components/Dropdown/DropdownItem.svelte
- src/views/projects/BranchSelector.svelte
- src/views/projects/Cob/CobStateButton.svelte
- src/views/projects/Cob/Revision.svelte
- src/views/projects/Issue.svelte
- src/views/projects/Patch.svelte
- src/views/projects/PeerSelector.svelte
The `Dropdown` component has gotten used in too many different places and with too many different use cases(badges, titles, styling, etc.)
I propose to remove features from the component and only provide a wrapper consisting in a button and a `Floating` modal that shows up, the design and composition of the Dropdown entries should be responsibility of the parent component.
Scrolling PeerSelector
https://github.com/radicle-dev/radicle-interface/assets/7912302/9d5d0c51-6681-4324-bee8-ca68c0313a3a
Closes #782, #730
> Refactor Dropdown component

- httpd-client/lib/project/patch.ts
- src/components/Authorship.svelte
- src/views/projects/Cob/Revision.svelte
- src/views/projects/Patch.svelte
This PR adds alias to Patch view. You should see 5 instances of alias in this image:
> Add `alias` to `Patch`

- scripts/check
To speed up local development.
Before: `./scripts/check  26.39s user 1.53s system 208% cpu 13.368 total`.
After: `./scripts/check  12.71s user 0.95s system 200% cpu 6.825 total`.
> Cache eslint and prettier

- src/views/projects/Patch/PatchTeaser.svelte
We haven't specified the direction of the flexbox here, so it goes with column.
Also cleans up some css and divs.
**Current**
**Fixed**
Closes #796
> Fix wrapping of PatchTeaser

- src/config.json
It's not on the seed anymore. To avoid this console error:
> Remove radicle-git project from pinned projects

- src/views/projects/Header.svelte
- tests/e2e/hashRouter.spec.ts
- tests/e2e/historyRouter.spec.ts
> Display a seed URL that matches `isLocal` as `radicle.local`

- httpd-client/index.ts
- httpd-client/lib/project.ts
- httpd-client/lib/project/comment.ts
- httpd-client/lib/project/commit.ts
- httpd-client/lib/project/issue.ts
- httpd-client/lib/project/patch.ts
- httpd-client/lib/session.ts
- httpd-client/lib/shared.ts
This way we can deploy back-end API changes that are backwards compatible without breaking the UI.
The downside is that we might miss new fields that are added to `radicle-httpd`.
> Relax radicle-httpd API schema checking

- src/views/projects/Tree/Folder.svelte
This reduces requests to the backend when fetching a tree to only the required requests.
> Fetch tree only when it's expanded

- src/App/Header/Connect.svelte
- src/components/Command.svelte
- Increases height of `Command` component to 2rem and vertical aligns text
- Reduces margin in Clone modal, which seemed odd.
**Current**
**New**
Closes #817
> Increase height of `Command` component, change margins

- tests/e2e/project/patches.spec.ts
- tests/support/cobs/patch.ts
- tests/support/fixtures.ts
This PR adds more expects and cases to the revision selector.
- Making sure the visibility of the RevisionSelector is correct
- Validating the displayed content changes to the correct one before and after a revision change.
Closes #837
> Add more tests to revision selector

- httpd-client/index.ts
- src/App/Header/Connect.svelte
- src/App/Header/Connect/PortInput.svelte
- src/App/Header/Search.svelte
- src/App/Header/SearchResultsModal.svelte
- src/components/TextInput.svelte
- src/lib/httpd.ts
- src/lib/router.ts
- src/lib/utils.ts
- src/views/home/Index.svelte
- src/views/projects/Header.svelte
- src/views/projects/Issue.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
- src/views/seeds/View.svelte
- src/views/seeds/router.ts
- src/views/session/Index.svelte
- tests/e2e/hotkeys.spec.ts
- tests/e2e/httpd.spec.ts
- tests/unit/router.test.ts
We only support fetching the default httpd port (8080). This PR removes navigation to `radicle.local` which represents `0.0.0.0:8080`, and prepares the app for defining a custom port.
Adds a e2e test also to test that authenticating with a custom port works and navigates to the correct seed.
> Handle custom httpd port

- src/views/projects/Cob/Revision.svelte
Current (ordering in reverse list "HEAD on top"):
New (ordering from merge base on the top to HEAD bottom):
> Reverse commit ordering in patch revisions

- src/views/projects/Tree/Folder.svelte
The `expanded` and the `tree` variable should react to changes to the `currentPath`
Closes #862
> Expand browser tree when navigation through relative file links

- public/index.css
- src/views/projects/Header.svelte
- src/views/projects/View.svelte
- tests/support/fixtures.ts
- tests/visual/markdown.spec.ts
- tests/visual/mobile/cob.spec.ts
- tests/visual/mobile/project.spec.ts
> Fix padding issues in source browser on mobile

- src/views/projects/Commit/CommitTeaser.svelte
Add ability, if a commit description is available to click a button next to the commit message in a `CommitTeaser`
See https://github.com/radicle-dev/radicle-interface/assets/7912302/1f9bd228-5cf2-4182-b5db-e356f21e0d31
Screenshot:
Video:
https://github.com/radicle-dev/radicle-interface/assets/7912302/53e8c4c1-776b-4771-9ea6-5ce9eafa4415
Closes #813
> Add ability to expand a commit message

- tests/e2e/project/commits.spec.ts
Clicking on the commit message expand toggle, check the content and hide it.
Closes #875
> Add spec for expanding commit message

- .github/workflows/check-e2e.yml
- scripts/install-binaries
- tests/support/fixtures.ts
- tests/support/globalSetup.ts
- tests/support/support.ts
- tsconfig.json
It’s not necessary anymore to add the folder with the heartwood test binaries to `PATH` before running the end-to-end tests.
> Tests automatically use heartwood binaries from local test folder

- tests/support/setupVitest.ts
- vite.config.ts
The update to happy-dom 8.0 did remove the need to do the assignment hack in `setupVitest`
source: https://github.com/vitest-dev/vitest/issues/2305#issuecomment-1396387954
> Remove hack for `happy-dom`

- tests/visual/seed.spec.ts
Mocking seed project listing route, and sorting projects by `localeCompare`.
This should return projects always in the same order.
Since in production we aren't sorting projects yet, and don't show much information that requires us to sort them, I think this is more a test issue, that doesn't allow us to have a deterministic ordering of projects.
If at some point project sorting is introduced we can probably revert this PR
> Fix flaky seed listing

- src/lib/router.ts
- tests/unit/router.test.ts
We replace the tests for `routeToPath` with a test that calls `pathToRoute(routeToPath(route))`. These test do not only cover the assertions of the previous tests but also check an important invariant for route parsing and building.
I’m not using `test.each` here because this makes the tests less readable.
> Test that route building and parsing leave routes invariant

- src/App/Header/Search.svelte
- src/lib/router.ts
- src/views/projects/Cob/Revision.svelte
- src/views/projects/Commit/CommitTeaser.svelte
- src/views/projects/Header.svelte
- src/views/projects/Issues.svelte
- src/views/projects/Patch.svelte
- src/views/projects/Patches.svelte
- src/views/projects/SourceBrowser/FileDiff.svelte
- src/views/projects/SourceBrowser/FileLocationChange.svelte
- src/views/projects/SourceBrowsingHeader.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
- src/views/seeds/View.svelte
We pass down props only where it's needed.
TBD remove the following props from the top-level `ProjectsParams` and `ProjectLoadedParams` types:
```
hash?: string;
path?: string;
peer?: string;
revision?: string;
route?: string;
search?: string;
```
> Clean up project view props

- src/components/ProjectLink.svelte
- src/lib/router.ts
- src/views/projects/Cob/Revision.svelte
- src/views/projects/Commit/CommitTeaser.svelte
- src/views/projects/Header.svelte
- src/views/projects/ProjectMeta.svelte
- src/views/projects/SourceBrowsingHeader.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
We use the new parameter instead of the shared revision parameter.
We also restricted the allowed parameters that are used for project-relative
navigation. This allows us to better understand which of the parameters are
used.
> Use dedicated `commitId` parameter for commits route

- src/views/projects/Cob/ErrorModal.svelte
- src/views/projects/Issue.svelte
- tests/e2e/project/issues.spec.ts
- tests/support/fixtures.ts
Catches errors that can occur during issue editing, commenting and replying.
Also adds a `authenticatedPeer` fixture, which authenticates a `RadiclePeer` with `radicle-httpd`
Shows a display that tells the user something went wrong, and a `ErrorMessage` component to copy the message and stackTrace
Also when there is an issue while refreshing the issue with a GET request after the PATCH update action, we show a different error
Closes #793
> Add error handling for issue creation and commenting

- src/components/Comment.svelte
- src/components/Link.svelte
- src/components/Thread.svelte
- src/views/projects/Cob/Revision.svelte
- src/views/projects/Patch.svelte
- tests/e2e/project/patches.spec.ts
- tests/support/fixtures.ts
Moving the commit listing out of the revision timeline, improves the code somewhat, since the revision object isn't really a revision event like merge, review, etc.
> Separate commit listing from revision timeline

- src/views/projects/Commit/CommitTeaser.svelte
- src/views/projects/History.svelte
- src/views/projects/Issue/IssueTeaser.svelte
- src/views/projects/Issues.svelte
- src/views/projects/Patch.svelte
- src/views/projects/Patch/PatchTeaser.svelte
- src/views/projects/Patches.svelte
- src/views/projects/View.svelte
We don't want to have a custom way to do routing within project views.
> Get rid of project-specific routing

- src/components/ErrorMessage.svelte
- src/views/projects/Cob/Revision.svelte
- tests/support/fixtures.ts
- tests/visual/cob.spec.ts
This PR fixes some style regressions in the patch view
Solution: added a `.comment-review` class that adds the needed background-color
Solution: added a `min-height: 3rem;`
Solution: add a visual test to check this and add margin, add inheritance of txt size
> Fix some style regressions in patch view

- src/views/projects/BranchSelector.svelte
- src/views/projects/Browser.svelte
- src/views/projects/Commit.svelte
- src/views/projects/History.svelte
- src/views/projects/SourceBrowsingHeader.svelte
- src/views/projects/router.ts
We remove logic used in the `BranchSelector` component. Instead we restructure the component properties and rely on the `Browser`, `History` and `Commit` components to pass values that result in the same behavior.
The PR also includes a follow-up commit that simplifies the branch loading:
* Don’t load branches in `commits` view. We the branch selector is not enabled there.
* Don’t silently swallow errors when fetching branches. Let the route loading mechanism handle errors.
* Don’t use the default branch as the fallback for `branches`. They are allowed to be empty and the empty case is handled properly now.
> Remove unnecessary logic in BranchSelector

- src/lib/httpd.ts
We remove a couple of calls to `console.error()` in the code for the local node connection. It’s not necessary to log errors that are expected, for example, if the node is down.
> Only log errors when something unexpected happens in local node connection

- playwright.config.ts
- playwright.ipfs.config.ts
- tests/support/fixtures.ts
The end-to-end tests no run against the app served on port 3001 so that we don’t need to shut down the development server.
> Use non-dev port for webserver during end-to-end tests

- httpd-client/tests/support/globalSetup.ts
- tests/e2e/project/commits.spec.ts
- tests/e2e/project/issues.spec.ts
- tests/support/fixtures.ts
- tests/support/globalSetup.ts
- tests/support/peerManager.ts
To avoid port collisions between tests that can eventually run in parallel, we need to be able to generate random port numbers.
This commit generates random httpd port numbers for inline tests, while keeping the current palm seed with the default port number 8080.
Closes #913
> Allow httpd API ports to be generated random

- src/lib/router.ts
- src/views/projects/router.ts
- tests/e2e/hashRouter.spec.ts
- tests/e2e/historyRouter.spec.ts
We don’t replace the path when we navigate internally. This means we keep the hash part of the URL even if it is not part of the route and we can remove the workaround for that.
This also means that we keep the original URL if the parsed route would result in a different URL. This change is visible through a slight adjustments in the tests.
> Don’t replace path on internal navigation

- src/App/Header/Search.svelte
- src/components/Markdown.svelte
- src/views/projects/Blob.svelte
- src/views/projects/Browser.svelte
- src/views/projects/Readme.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
We stop handling the URL hash through the routing system. Hashes are local to the current view and can be handled by the shown components.
> Stop handling URL hash through routing

- .eslintrc.cjs
- package-lock.json
- package.json
- scripts/check
* We remove all styling related lints and use `eslint-config-prettier`. There’s no need to bother developers with styling lints because Prettier already takes care of that. (This is the [recommended integration with Prettier][1])
* We use the “warning” level for lints that are code style related. This allows developers to distinguish issues that need to be fixed now (like type errors) and issues that can be fixed later (like style errors). We do enforce all lints on CI by settings `--max-warnings=0`.
[1]: https://prettier.io/docs/en/integrating-with-linters.html
> Use ESlint warnings and Prettier config

- src/views/projects/BranchSelector.svelte
- src/views/projects/Browser.svelte
- src/views/projects/PeerSelector.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
This PR consists of two commits that remove redundant properties from the project route types.
We remove the requirement that `LoadedSourceBrowsingView` needs to be assignable to `ProjectParams["view"]`. This decouples `ProjectRoute` and `ProjectLoadedRoute` and lets us modify them independently.
I did not use a common `routeParamsView` function because I prefer the flexibility of being able to modify them independently while this area of code changes a lot.
> Remove redundant project route props

- httpd-client/lib/project.ts
- httpd-client/lib/project/patch.ts
- httpd-client/lib/session.ts
- httpd-client/tests/client.test.ts
- httpd-client/tests/project.test.ts
- httpd-client/tests/session.test.ts
- httpd-client/tests/support/fixtures.ts
- httpd-client/tests/support/globalSetup.ts
- httpd-client/tests/support/httpd.ts
- httpd-client/tests/support/support.ts
- httpd-client/vite.config.ts
- package.json
This PR tests some of the missing httpd endpoints and adds some more.
Also adds a `httpd` fixture to the httpd-api unit tests that setups a `RadiclePeer` and a `HttpdClient` to do some nice stuff
And we have enough test isolation to run these tests in parallel with more than one thread.
See commits for more information
Closes #896 
Closes #915
> Add missing httpd api tests

- src/views/projects/Commit.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
We move the `peer` and `revision` properties from the shared `ProjectLoadedParams` interface to the `tree` and `history` subroutes where they are needed.
> Cleanup shared peer and revision props for project route

- index.html
- src/App.svelte
- src/lib/router.ts
- src/views/home/Index.svelte
- src/views/projects/router.ts
- src/views/seeds/View.svelte
This improves UX making it easier to find the tab that I'm looking for when I have multiple tabs open.
We can come up with a more elaborate structure, but for now this might be sufficient.
> Set page title in the router

- src/views/projects/Cob/Revision.svelte
Fixes: https://github.com/radicle-dev/radicle-interface/issues/940.
Turns out we did have a visual spec for this:
> Reverse revision commit ordering

- src/components/Markdown.svelte
- tests/e2e/project.spec.ts
- tests/support/fixtures.ts
Fixes #928
Also includes a commit that improves Playwright route mocking:
We determine URLs to mock with a URL matcher instead of mocking every URL and determining the behavior in the route handler. This should be slightly faster and should result in better debugging experience because we don’t come across the `route.continue()` event that often.
> Don’t intercept navigation to external URLs in Markdown

- src/App/Header/Search.svelte
- src/App/Header/SearchResultsModal.svelte
- src/lib/router.ts
- src/lib/router/definitions.ts
- src/views/home/Index.svelte
- src/views/projects/BranchSelector.svelte
- src/views/projects/Cob/Revision.svelte
- src/views/projects/Commit/CommitTeaser.svelte
- src/views/projects/Header.svelte
- src/views/projects/History.svelte
- src/views/projects/Issue.svelte
- src/views/projects/Issue/IssueTeaser.svelte
- src/views/projects/Issue/New.svelte
- src/views/projects/Issues.svelte
- src/views/projects/Patch.svelte
- src/views/projects/Patch/PatchTeaser.svelte
- src/views/projects/Patches.svelte
- src/views/projects/PeerSelector.svelte
- src/views/projects/ProjectMeta.svelte
- src/views/projects/Readme.svelte
- src/views/projects/SourceBrowser/FileDiff.svelte
- src/views/projects/SourceBrowser/FileLocationChange.svelte
- src/views/projects/SourceBrowsingHeader.svelte
- src/views/projects/Tree.svelte
- src/views/projects/Tree/Folder.svelte
- src/views/projects/router.ts
- src/views/seeds/View.svelte
- tests/e2e/project/commit.spec.ts
- tests/unit/router.test.ts
We switch to a project route type that is just a union. This has the following advantages
* It’s much easier to construct project routes. Fewer properties are needed and there are no nested objects.
* We eliminate the implicitly shared properties `path`, `peer`, `revision` and `route` which only belonged to the tree route.
* The structure of the project route is more regular and thus easier to understand.
> Switch to flat project route type

- src/lib/router.ts
- tests/unit/router.test.ts
We switch the test for `pathToRoute` from a paramterized test to regular tests. I had a lot of trouble finding the right properties to change when a test in this group failed. The line number was not helpful at all and the test description was burried inside an object.
We also rename `pathToRoute` to `urlToRoute` because the function takes a `URL` as an argument.
> Make pathToRoute tests more readable

- httpd-client/tests/client.test.ts
- httpd-client/tests/project.test.ts
- httpd-client/tests/support/globalSetup.ts
- src/lib/config.ts
- src/lib/httpd.ts
- src/lib/router.ts
- tests/support/fixtures.ts
- tests/support/globalSetup.ts
- tests/unit/router.test.ts
- vite.config.ts
Also where possible use the `config.seeds.defaultHttpdPort` instead of hardcoding it.
This helps, when developers already have a `radicle-httpd` process running on their machines.
Also makes running the web client on a non 8080 port more stable.
> Set the `httpd` port for the test suite to be 8081.

- package-lock.json
- package.json
- src/lib/markdown.ts
- src/views/projects/ProjectMeta.svelte
Uses `marked-linkify-it` to generate auto-linking in comments and other places we use markdown
Also allows us to generate auto-references in the future to detect a ObjectId and generate a link to the issue or patch in question. 🎉 
~Currently still pending since there are no types for `marked-linkify-it` but there is a PR for that.
https://github.com/UziTech/marked-linkify-it/pull/385~
Closes #880
> Add auto-linking in markdown

- src/App/Header.svelte
- tests/build/smoke.spec.ts
- tests/e2e/clipboard.spec.ts
- tests/e2e/hashRouter.spec.ts
- tests/e2e/historyRouter.spec.ts
- tests/e2e/landingPage.spec.ts
- tests/e2e/project.spec.ts
- tests/e2e/project/commit.spec.ts
- tests/e2e/project/issues.spec.ts
- tests/e2e/project/patches.spec.ts
- tests/e2e/seed.spec.ts
- tests/e2e/settings.spec.ts
- tests/visual/markdown.spec.ts
- tests/visual/mobile/project.spec.ts
- tests/visual/project.spec.ts
- 6151729a6d4555076a903e415762ffcc8d9a6e79 Add empty file e2e test case
- afbc57079bb6d7a1a566948ec8a12821e9a33d65 Rename `locator("text"` and `locator("role=` to `getByText` and `getByRole`
Close #936
> Add missing test cases

- src/views/projects/BranchSelector.svelte
- src/views/projects/PeerSelector.svelte
- src/views/projects/SourceBrowsingHeader.svelte
We greatly reduce the numbers of properties that need to be passed to `BranchSelector` and `PeerSelector` by constructing routes in `SourceBrowsingHeader`. We’ll lift the logic out of `SourceBrowsingHeader` in a follow-up.
> Simplify BranchSelector and PeerSelector props

- src/views/projects/SourceBrowser/FileDiff.svelte
- tests/e2e/project.spec.ts
- tests/visual/project.spec.ts
Right now I'm using screenshots to reference a specific part of a diff. A better option would be a link, like GitHub.
For example the link for the picture would be:
`/seeds/radicle.local/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/patches/e6d27cade05288b5bfa79f0e3c47bb07fdc3c2a0?diff=1ddfa4fe94adca5096a82316fbaf7b147e3b5d9a..5242a14b5e9fefd07db040940223b7f37ba72988#radicle-cli/src/commands/patch/edit.rsH1R9`
0. Right now, the link wouldn't scroll to the line, as we load things in 2 stages, but it shouldn't matter as we're eventually moving to a single stage. Scrolls on GitHub doesn't work that well either anyway, highlighting is the most important part.
1. GitHub uses a different format, `#diff-86922c6cf991e9927a1a37a653efc6e9c1db5dfacb4a99a772798d30d4b0f3dbR69`, we can achieve a similar format by …
> Make diff line selectable and shareable

- src/views/projects/Commit.svelte
- src/views/projects/Header.svelte
- src/views/projects/Issue.svelte
- src/views/projects/Patch.svelte
- src/views/projects/SourceBrowsingHeader.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
For a single commit view the source browsing header (peer selector, branch selector, commits, contributor count) does not contain meaningful information. We remove the header and simply show the commit.
See #938.
Before:
After:
> Remove source browsing header from commit view

- src/views/projects/BranchSelector.svelte
There’s no need for the outer `if branches.length > 0`. We already disable the dropdown unless `branches.length > 1`.
> Simplify BranchSelector

- src/views/projects/Browser.svelte
- src/views/projects/History.svelte
- src/views/projects/SourceBrowsingHeader.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
We prepare the data for `PeerSelector` and `BranchSelector` in the `History` and `Browser` instead of `SourceBrowsingHeader`. This makes the component APIs overall simpler and allows us to remove `LoadedSourceBrowsingView`.
> Lift branch/peer selector data into main views

- src/views/projects/Browser.svelte
- src/views/projects/History.svelte
- src/views/projects/SourceBrowsingHeader.svelte
- src/views/projects/View.svelte
- src/views/projects/router.ts
We simplify the `History`, `Browser` and `SourceBrowsingHeader` components by requiring fewer props and streamlining the view shape.
> Simplify History, Browser and SourceBrowsingHeader props

- src/views/projects/Browser.svelte
- src/views/projects/Tree.svelte
- src/views/projects/Tree/Folder.svelte
- tests/e2e/hashRouter.spec.ts
- tests/e2e/historyRouter.spec.ts
This fixes not being able to navigate to the commit history while a file is selected on the default peer/branch.
> Fix navigating to history when a file is selected

- .prettierrc
- package.json
- [prettier assumes now that we want to ignore files listed in .gitignore by default](https://prettier.io/blog/2023/07/05/3.0.0.html#ignore-gitignored-files-by-default-14731httpsgithubcomprettierprettierpull14731-by-fiskerhttpsgithubcomfisker)
- [trailingComma: all is now the default value](https://prettier.io/blog/2023/07/05/3.0.0.html#change-the-default-value-for-trailingcomma-to-all-11479httpsgithubcomprettierprettierpull11479-by-fiskerhttpsgithubcomfisker-13143httpsgithubcomprettierprettierpull13143-by-sosukesuzukihttpsgithubcomsosukesuzuki)
Related: #977
> prettier: Remove some values that are now defaults

- tests/e2e/project/issues.spec.ts
- tests/e2e/project/patches.spec.ts
When creating a new patch or issue, we want the counters to reflect on that on navigation.
Closes #974
> tests: Add e2e tests for patch and issue counters

- src/views/seeds/router.ts
- tests/visual/seed.spec.ts
Uses the projects activity, fetched from `/projects/${id}/activity` which is an array of commit timestamps.
So could suffer from some errors if commits with non current timestamps are being used.
Closes #967
> Sort projects in seed view by most recent activity

- src/App/Header/Connect.svelte
- src/config.json
- src/lib/config.ts
- src/lib/httpd.ts
- tests/e2e/httpd.spec.ts
- tests/support/fixtures.ts
Instead of using always the `config.seeds.defaultHttpdPort` which is 443, we should take into account the `customPort` variable that is set by the user.
Also adds a `config.defaultLocalHttpdPort` so we can define what we want the local httpd port to be in production.
Closes #965
> fix: Change `rad web` command when httpd port changes

- httpd-client/lib/project/commit.ts
Adds new `parents` property on `CommitHeader` introduced in https://app.radicle.xyz/nodes/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/commits/5cb4d5cd7629d30e95413d91356d1182d34383f1
> Add `parents` property to `CommitHeader` type

- tests/visual/project.spec.ts
This was failing on master, so the visual spec cache didn't get updated.
> Fix visual tests

- src/views/nodes/router.ts
> Fix project sorting on node page when there is no activity data

- httpd-client/lib/project.ts
- src/views/nodes/View.svelte
- src/views/nodes/router.ts
Instead of going with project activity which is being stripped everything that is older than one year, we should look at the current project head time.
> Sort node projects by HEAD commit time

- src/components/ProjectCard.svelte
- src/views/nodes/View.svelte
This fix a regression we started to have after #1002, when starting to sort projects after loading more.
Fixed by adding a key to the each loop.
> Add key to each loop in project listing

- src/views/nodes/router.ts
- tests/e2e/project.spec.ts
We only show "Node not found" on load errors. All other errors will be rethrown.
> Improve node view error handling

- src/App.svelte
- src/lib/httpd.ts
- src/views/home/Index.svelte
- src/views/home/router.ts
- tests/e2e/landingPage.spec.ts
- tests/support/fixtures.ts
- tests/visual/landingPage.spec.ts
This PR shows either the projects found on a local node to the landing page, or fallback to the pinned ones in `config.projects.pinned`
> Add local projects to landing page, if available

- vite.config.ts
Okay let's rewrite this.. 😀 
So the issue is that having one vite dev server running on one port, and then starting the e2e or httpd-api test suite with playwright, there are moments that the vite dev server gets restarted due to changes to either `vite.config.ts` or `svelte.config.js`, 
So this PR adds the following glob patterns to be ignored by the vite file watcher, since they aren't code that we change often, and don't think we need hot reload for it.
```
[
"**/vite.config.ts/**",
"**/svelte.config.js/**",
],
```
So if we ignore those patterns for the vite file watcher (uses chokidar) the tests are running fine, and we still have hot reload for all the other files
> Fix vite reloading during e2e tests

- tests/e2e/hotkeys.spec.ts
- tests/e2e/project/patches.spec.ts
Reduces the amount of work done by the `go through the entire ui patch flow` test.
Splitting it into multiple smaller tests, testing a specific part of the patch UI flow.
Closes #1036
> Split going through UI patch flow into separate tests

- httpd-client/index.ts
- httpd-client/lib/project.ts
- src/views/projects/Changeset.svelte
- src/views/projects/Changeset/FileDiff.svelte
- src/views/projects/Changeset/FileLocationChange.svelte
- src/views/projects/Patch.svelte
- src/views/projects/router.ts
- tests/e2e/project/patches.spec.ts
Instead of navigating users to the patch revision as a repo commit, we should let users navigate to the most recent commit that file has had, which we can get from the diff response on `files[blob].lastCommit.id`
UPDATE: This PR disables the `View File` navigation for moved or copied files, since they don't return a lastCommit blob where we can navigate to, once the mentioned `radicle-surf` PR has a release and can be added to heartwood, we can update them too, in the meantime I don't think we should keep a broken navigation displayed..
Closes #1040
> Use `lastCommit` of each blob for navigation instead of patch revision

- httpd-client/index.ts
- httpd-client/lib/project/commit.ts
- src/views/projects/Changeset.svelte
- tests/e2e/project/commit.spec.ts
libgit2 optimizes around not loading the content, when there's no content callbacks configured.
So we aren't able to get a clear answer from radicle-surf if a file in a diff is a binary or not.
A simple way without doing additional API requests is to check if the file type is a executable and if there are no hunks (since we don't get any deltas in binaries), this is a strong
indicator for a binary.
References:
https://github.com/libgit2/libgit2/issues/6637#issuecomment-1733118686
https://github.com/rust-lang/git2-rs/issues/991
Closes #1039
> Improve binary detection

- tests/e2e/hotkeys.spec.ts
Before starting to type `searchquery` we should probably wait for the text field to be expanded.
> Reduce test flakiness on global hotkeys
